// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: worker/v1/worker.proto

package workerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerService_EnqueueJob_FullMethodName        = "/social_backend.worker.v1.WorkerService/EnqueueJob"
	WorkerService_ClaimJob_FullMethodName          = "/social_backend.worker.v1.WorkerService/ClaimJob"
	WorkerService_CompleteJob_FullMethodName       = "/social_backend.worker.v1.WorkerService/CompleteJob"
	WorkerService_FailJob_FullMethodName           = "/social_backend.worker.v1.WorkerService/FailJob"
	WorkerService_ListJobs_FullMethodName          = "/social_backend.worker.v1.WorkerService/ListJobs"
	WorkerService_ExecuteNext_FullMethodName       = "/social_backend.worker.v1.WorkerService/ExecuteNext"
	WorkerService_ExecuteUntilEmpty_FullMethodName = "/social_backend.worker.v1.WorkerService/ExecuteUntilEmpty"
)

// WorkerServiceClient is the client API for WorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerServiceClient interface {
	EnqueueJob(ctx context.Context, in *EnqueueJobRequest, opts ...grpc.CallOption) (*Job, error)
	ClaimJob(ctx context.Context, in *ClaimJobRequest, opts ...grpc.CallOption) (*Job, error)
	CompleteJob(ctx context.Context, in *TransitionJobRequest, opts ...grpc.CallOption) (*Job, error)
	FailJob(ctx context.Context, in *TransitionJobRequest, opts ...grpc.CallOption) (*Job, error)
	ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
	ExecuteNext(ctx context.Context, in *ExecuteNextRequest, opts ...grpc.CallOption) (*ExecutionResult, error)
	ExecuteUntilEmpty(ctx context.Context, in *ExecuteUntilEmptyRequest, opts ...grpc.CallOption) (*ExecutionResult, error)
}

type workerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServiceClient(cc grpc.ClientConnInterface) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) EnqueueJob(ctx context.Context, in *EnqueueJobRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, WorkerService_EnqueueJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ClaimJob(ctx context.Context, in *ClaimJobRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, WorkerService_ClaimJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) CompleteJob(ctx context.Context, in *TransitionJobRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, WorkerService_CompleteJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) FailJob(ctx context.Context, in *TransitionJobRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, WorkerService_FailJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, WorkerService_ListJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ExecuteNext(ctx context.Context, in *ExecuteNextRequest, opts ...grpc.CallOption) (*ExecutionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionResult)
	err := c.cc.Invoke(ctx, WorkerService_ExecuteNext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ExecuteUntilEmpty(ctx context.Context, in *ExecuteUntilEmptyRequest, opts ...grpc.CallOption) (*ExecutionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionResult)
	err := c.cc.Invoke(ctx, WorkerService_ExecuteUntilEmpty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServiceServer is the server API for WorkerService service.
// All implementations must embed UnimplementedWorkerServiceServer
// for forward compatibility.
type WorkerServiceServer interface {
	EnqueueJob(context.Context, *EnqueueJobRequest) (*Job, error)
	ClaimJob(context.Context, *ClaimJobRequest) (*Job, error)
	CompleteJob(context.Context, *TransitionJobRequest) (*Job, error)
	FailJob(context.Context, *TransitionJobRequest) (*Job, error)
	ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error)
	ExecuteNext(context.Context, *ExecuteNextRequest) (*ExecutionResult, error)
	ExecuteUntilEmpty(context.Context, *ExecuteUntilEmptyRequest) (*ExecutionResult, error)
	mustEmbedUnimplementedWorkerServiceServer()
}

// UnimplementedWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServiceServer struct{}

func (UnimplementedWorkerServiceServer) EnqueueJob(context.Context, *EnqueueJobRequest) (*Job, error) {
	return nil, status.Error(codes.Unimplemented, "method EnqueueJob not implemented")
}
func (UnimplementedWorkerServiceServer) ClaimJob(context.Context, *ClaimJobRequest) (*Job, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimJob not implemented")
}
func (UnimplementedWorkerServiceServer) CompleteJob(context.Context, *TransitionJobRequest) (*Job, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteJob not implemented")
}
func (UnimplementedWorkerServiceServer) FailJob(context.Context, *TransitionJobRequest) (*Job, error) {
	return nil, status.Error(codes.Unimplemented, "method FailJob not implemented")
}
func (UnimplementedWorkerServiceServer) ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedWorkerServiceServer) ExecuteNext(context.Context, *ExecuteNextRequest) (*ExecutionResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteNext not implemented")
}
func (UnimplementedWorkerServiceServer) ExecuteUntilEmpty(context.Context, *ExecuteUntilEmptyRequest) (*ExecutionResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteUntilEmpty not implemented")
}
func (UnimplementedWorkerServiceServer) mustEmbedUnimplementedWorkerServiceServer() {}
func (UnimplementedWorkerServiceServer) testEmbeddedByValue()                       {}

// UnsafeWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServiceServer will
// result in compilation errors.
type UnsafeWorkerServiceServer interface {
	mustEmbedUnimplementedWorkerServiceServer()
}

func RegisterWorkerServiceServer(s grpc.ServiceRegistrar, srv WorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerService_ServiceDesc, srv)
}

func _WorkerService_EnqueueJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).EnqueueJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_EnqueueJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).EnqueueJob(ctx, req.(*EnqueueJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ClaimJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ClaimJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ClaimJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ClaimJob(ctx, req.(*ClaimJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_CompleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransitionJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).CompleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_CompleteJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).CompleteJob(ctx, req.(*TransitionJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_FailJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransitionJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).FailJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_FailJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).FailJob(ctx, req.(*TransitionJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ListJobs(ctx, req.(*ListJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ExecuteNext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteNextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ExecuteNext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ExecuteNext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ExecuteNext(ctx, req.(*ExecuteNextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ExecuteUntilEmpty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteUntilEmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ExecuteUntilEmpty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ExecuteUntilEmpty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ExecuteUntilEmpty(ctx, req.(*ExecuteUntilEmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerService_ServiceDesc is the grpc.ServiceDesc for WorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "social_backend.worker.v1.WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnqueueJob",
			Handler:    _WorkerService_EnqueueJob_Handler,
		},
		{
			MethodName: "ClaimJob",
			Handler:    _WorkerService_ClaimJob_Handler,
		},
		{
			MethodName: "CompleteJob",
			Handler:    _WorkerService_CompleteJob_Handler,
		},
		{
			MethodName: "FailJob",
			Handler:    _WorkerService_FailJob_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _WorkerService_ListJobs_Handler,
		},
		{
			MethodName: "ExecuteNext",
			Handler:    _WorkerService_ExecuteNext_Handler,
		},
		{
			MethodName: "ExecuteUntilEmpty",
			Handler:    _WorkerService_ExecuteUntilEmpty_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "worker/v1/worker.proto",
}
