// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: gateway.proto

package gatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayService_ResolveSession_FullMethodName           = "/social_backend.gateway.v1.GatewayService/ResolveSession"
	GatewayService_ConnectPresence_FullMethodName          = "/social_backend.gateway.v1.GatewayService/ConnectPresence"
	GatewayService_HeartbeatPresence_FullMethodName        = "/social_backend.gateway.v1.GatewayService/HeartbeatPresence"
	GatewayService_DisconnectPresence_FullMethodName       = "/social_backend.gateway.v1.GatewayService/DisconnectPresence"
	GatewayService_HandshakeRealtime_FullMethodName        = "/social_backend.gateway.v1.GatewayService/HandshakeRealtime"
	GatewayService_ResumeRealtime_FullMethodName           = "/social_backend.gateway.v1.GatewayService/ResumeRealtime"
	GatewayService_HeartbeatRealtime_FullMethodName        = "/social_backend.gateway.v1.GatewayService/HeartbeatRealtime"
	GatewayService_CloseRealtime_FullMethodName            = "/social_backend.gateway.v1.GatewayService/CloseRealtime"
	GatewayService_GetRealtimeSession_FullMethodName       = "/social_backend.gateway.v1.GatewayService/GetRealtimeSession"
	GatewayService_GetRealtimeSessionEvents_FullMethodName = "/social_backend.gateway.v1.GatewayService/GetRealtimeSessionEvents"
	GatewayService_DispatchChat_FullMethodName             = "/social_backend.gateway.v1.GatewayService/DispatchChat"
	GatewayService_AckConversation_FullMethodName          = "/social_backend.gateway.v1.GatewayService/AckConversation"
	GatewayService_ReplayMessages_FullMethodName           = "/social_backend.gateway.v1.GatewayService/ReplayMessages"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayServiceClient interface {
	ResolveSession(ctx context.Context, in *ResolveSessionRequest, opts ...grpc.CallOption) (*Subject, error)
	ConnectPresence(ctx context.Context, in *SessionPresenceUpdate, opts ...grpc.CallOption) (*PresenceSnapshot, error)
	HeartbeatPresence(ctx context.Context, in *SessionPresenceUpdate, opts ...grpc.CallOption) (*PresenceSnapshot, error)
	DisconnectPresence(ctx context.Context, in *SessionPresenceUpdate, opts ...grpc.CallOption) (*PresenceSnapshot, error)
	HandshakeRealtime(ctx context.Context, in *HandshakeRealtimeRequest, opts ...grpc.CallOption) (*RealtimeSession, error)
	ResumeRealtime(ctx context.Context, in *ResumeRealtimeRequest, opts ...grpc.CallOption) (*RealtimeSession, error)
	HeartbeatRealtime(ctx context.Context, in *RealtimeSessionRequest, opts ...grpc.CallOption) (*RealtimeSession, error)
	CloseRealtime(ctx context.Context, in *RealtimeSessionRequest, opts ...grpc.CallOption) (*RealtimeSession, error)
	GetRealtimeSession(ctx context.Context, in *RealtimeSessionRequest, opts ...grpc.CallOption) (*RealtimeSession, error)
	GetRealtimeSessionEvents(ctx context.Context, in *RealtimeSessionRequest, opts ...grpc.CallOption) (*SessionEventInbox, error)
	DispatchChat(ctx context.Context, in *DispatchChatRequest, opts ...grpc.CallOption) (*DispatchChatResponse, error)
	AckConversation(ctx context.Context, in *AckConversationRequest, opts ...grpc.CallOption) (*AckConversationResponse, error)
	ReplayMessages(ctx context.Context, in *ReplayMessagesRequest, opts ...grpc.CallOption) (*ReplayMessagesResponse, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) ResolveSession(ctx context.Context, in *ResolveSessionRequest, opts ...grpc.CallOption) (*Subject, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Subject)
	err := c.cc.Invoke(ctx, GatewayService_ResolveSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ConnectPresence(ctx context.Context, in *SessionPresenceUpdate, opts ...grpc.CallOption) (*PresenceSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PresenceSnapshot)
	err := c.cc.Invoke(ctx, GatewayService_ConnectPresence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) HeartbeatPresence(ctx context.Context, in *SessionPresenceUpdate, opts ...grpc.CallOption) (*PresenceSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PresenceSnapshot)
	err := c.cc.Invoke(ctx, GatewayService_HeartbeatPresence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) DisconnectPresence(ctx context.Context, in *SessionPresenceUpdate, opts ...grpc.CallOption) (*PresenceSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PresenceSnapshot)
	err := c.cc.Invoke(ctx, GatewayService_DisconnectPresence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) HandshakeRealtime(ctx context.Context, in *HandshakeRealtimeRequest, opts ...grpc.CallOption) (*RealtimeSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RealtimeSession)
	err := c.cc.Invoke(ctx, GatewayService_HandshakeRealtime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ResumeRealtime(ctx context.Context, in *ResumeRealtimeRequest, opts ...grpc.CallOption) (*RealtimeSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RealtimeSession)
	err := c.cc.Invoke(ctx, GatewayService_ResumeRealtime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) HeartbeatRealtime(ctx context.Context, in *RealtimeSessionRequest, opts ...grpc.CallOption) (*RealtimeSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RealtimeSession)
	err := c.cc.Invoke(ctx, GatewayService_HeartbeatRealtime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) CloseRealtime(ctx context.Context, in *RealtimeSessionRequest, opts ...grpc.CallOption) (*RealtimeSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RealtimeSession)
	err := c.cc.Invoke(ctx, GatewayService_CloseRealtime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetRealtimeSession(ctx context.Context, in *RealtimeSessionRequest, opts ...grpc.CallOption) (*RealtimeSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RealtimeSession)
	err := c.cc.Invoke(ctx, GatewayService_GetRealtimeSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetRealtimeSessionEvents(ctx context.Context, in *RealtimeSessionRequest, opts ...grpc.CallOption) (*SessionEventInbox, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionEventInbox)
	err := c.cc.Invoke(ctx, GatewayService_GetRealtimeSessionEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) DispatchChat(ctx context.Context, in *DispatchChatRequest, opts ...grpc.CallOption) (*DispatchChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchChatResponse)
	err := c.cc.Invoke(ctx, GatewayService_DispatchChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) AckConversation(ctx context.Context, in *AckConversationRequest, opts ...grpc.CallOption) (*AckConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckConversationResponse)
	err := c.cc.Invoke(ctx, GatewayService_AckConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ReplayMessages(ctx context.Context, in *ReplayMessagesRequest, opts ...grpc.CallOption) (*ReplayMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplayMessagesResponse)
	err := c.cc.Invoke(ctx, GatewayService_ReplayMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility.
type GatewayServiceServer interface {
	ResolveSession(context.Context, *ResolveSessionRequest) (*Subject, error)
	ConnectPresence(context.Context, *SessionPresenceUpdate) (*PresenceSnapshot, error)
	HeartbeatPresence(context.Context, *SessionPresenceUpdate) (*PresenceSnapshot, error)
	DisconnectPresence(context.Context, *SessionPresenceUpdate) (*PresenceSnapshot, error)
	HandshakeRealtime(context.Context, *HandshakeRealtimeRequest) (*RealtimeSession, error)
	ResumeRealtime(context.Context, *ResumeRealtimeRequest) (*RealtimeSession, error)
	HeartbeatRealtime(context.Context, *RealtimeSessionRequest) (*RealtimeSession, error)
	CloseRealtime(context.Context, *RealtimeSessionRequest) (*RealtimeSession, error)
	GetRealtimeSession(context.Context, *RealtimeSessionRequest) (*RealtimeSession, error)
	GetRealtimeSessionEvents(context.Context, *RealtimeSessionRequest) (*SessionEventInbox, error)
	DispatchChat(context.Context, *DispatchChatRequest) (*DispatchChatResponse, error)
	AckConversation(context.Context, *AckConversationRequest) (*AckConversationResponse, error)
	ReplayMessages(context.Context, *ReplayMessagesRequest) (*ReplayMessagesResponse, error)
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) ResolveSession(context.Context, *ResolveSessionRequest) (*Subject, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveSession not implemented")
}
func (UnimplementedGatewayServiceServer) ConnectPresence(context.Context, *SessionPresenceUpdate) (*PresenceSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectPresence not implemented")
}
func (UnimplementedGatewayServiceServer) HeartbeatPresence(context.Context, *SessionPresenceUpdate) (*PresenceSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method HeartbeatPresence not implemented")
}
func (UnimplementedGatewayServiceServer) DisconnectPresence(context.Context, *SessionPresenceUpdate) (*PresenceSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method DisconnectPresence not implemented")
}
func (UnimplementedGatewayServiceServer) HandshakeRealtime(context.Context, *HandshakeRealtimeRequest) (*RealtimeSession, error) {
	return nil, status.Error(codes.Unimplemented, "method HandshakeRealtime not implemented")
}
func (UnimplementedGatewayServiceServer) ResumeRealtime(context.Context, *ResumeRealtimeRequest) (*RealtimeSession, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeRealtime not implemented")
}
func (UnimplementedGatewayServiceServer) HeartbeatRealtime(context.Context, *RealtimeSessionRequest) (*RealtimeSession, error) {
	return nil, status.Error(codes.Unimplemented, "method HeartbeatRealtime not implemented")
}
func (UnimplementedGatewayServiceServer) CloseRealtime(context.Context, *RealtimeSessionRequest) (*RealtimeSession, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseRealtime not implemented")
}
func (UnimplementedGatewayServiceServer) GetRealtimeSession(context.Context, *RealtimeSessionRequest) (*RealtimeSession, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRealtimeSession not implemented")
}
func (UnimplementedGatewayServiceServer) GetRealtimeSessionEvents(context.Context, *RealtimeSessionRequest) (*SessionEventInbox, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRealtimeSessionEvents not implemented")
}
func (UnimplementedGatewayServiceServer) DispatchChat(context.Context, *DispatchChatRequest) (*DispatchChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DispatchChat not implemented")
}
func (UnimplementedGatewayServiceServer) AckConversation(context.Context, *AckConversationRequest) (*AckConversationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckConversation not implemented")
}
func (UnimplementedGatewayServiceServer) ReplayMessages(context.Context, *ReplayMessagesRequest) (*ReplayMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplayMessages not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue()                        {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_ResolveSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ResolveSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ResolveSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ResolveSession(ctx, req.(*ResolveSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ConnectPresence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionPresenceUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ConnectPresence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ConnectPresence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ConnectPresence(ctx, req.(*SessionPresenceUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_HeartbeatPresence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionPresenceUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).HeartbeatPresence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_HeartbeatPresence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).HeartbeatPresence(ctx, req.(*SessionPresenceUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_DisconnectPresence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionPresenceUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).DisconnectPresence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_DisconnectPresence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).DisconnectPresence(ctx, req.(*SessionPresenceUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_HandshakeRealtime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRealtimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).HandshakeRealtime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_HandshakeRealtime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).HandshakeRealtime(ctx, req.(*HandshakeRealtimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ResumeRealtime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRealtimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ResumeRealtime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ResumeRealtime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ResumeRealtime(ctx, req.(*ResumeRealtimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_HeartbeatRealtime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RealtimeSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).HeartbeatRealtime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_HeartbeatRealtime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).HeartbeatRealtime(ctx, req.(*RealtimeSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_CloseRealtime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RealtimeSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).CloseRealtime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_CloseRealtime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).CloseRealtime(ctx, req.(*RealtimeSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetRealtimeSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RealtimeSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetRealtimeSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetRealtimeSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetRealtimeSession(ctx, req.(*RealtimeSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetRealtimeSessionEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RealtimeSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetRealtimeSessionEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetRealtimeSessionEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetRealtimeSessionEvents(ctx, req.(*RealtimeSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_DispatchChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).DispatchChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_DispatchChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).DispatchChat(ctx, req.(*DispatchChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_AckConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).AckConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_AckConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).AckConversation(ctx, req.(*AckConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ReplayMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplayMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ReplayMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ReplayMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ReplayMessages(ctx, req.(*ReplayMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "social_backend.gateway.v1.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveSession",
			Handler:    _GatewayService_ResolveSession_Handler,
		},
		{
			MethodName: "ConnectPresence",
			Handler:    _GatewayService_ConnectPresence_Handler,
		},
		{
			MethodName: "HeartbeatPresence",
			Handler:    _GatewayService_HeartbeatPresence_Handler,
		},
		{
			MethodName: "DisconnectPresence",
			Handler:    _GatewayService_DisconnectPresence_Handler,
		},
		{
			MethodName: "HandshakeRealtime",
			Handler:    _GatewayService_HandshakeRealtime_Handler,
		},
		{
			MethodName: "ResumeRealtime",
			Handler:    _GatewayService_ResumeRealtime_Handler,
		},
		{
			MethodName: "HeartbeatRealtime",
			Handler:    _GatewayService_HeartbeatRealtime_Handler,
		},
		{
			MethodName: "CloseRealtime",
			Handler:    _GatewayService_CloseRealtime_Handler,
		},
		{
			MethodName: "GetRealtimeSession",
			Handler:    _GatewayService_GetRealtimeSession_Handler,
		},
		{
			MethodName: "GetRealtimeSessionEvents",
			Handler:    _GatewayService_GetRealtimeSessionEvents_Handler,
		},
		{
			MethodName: "DispatchChat",
			Handler:    _GatewayService_DispatchChat_Handler,
		},
		{
			MethodName: "AckConversation",
			Handler:    _GatewayService_AckConversation_Handler,
		},
		{
			MethodName: "ReplayMessages",
			Handler:    _GatewayService_ReplayMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}
