// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gateway/v1/gateway.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Subject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subject) Reset() {
	*x = Subject{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subject) ProtoMessage() {}

func (x *Subject) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subject.ProtoReflect.Descriptor instead.
func (*Subject) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *Subject) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Subject) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type SessionPresenceUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RealmId       string                 `protobuf:"bytes,3,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionPresenceUpdate) Reset() {
	*x = SessionPresenceUpdate{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionPresenceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionPresenceUpdate) ProtoMessage() {}

func (x *SessionPresenceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionPresenceUpdate.ProtoReflect.Descriptor instead.
func (*SessionPresenceUpdate) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *SessionPresenceUpdate) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SessionPresenceUpdate) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionPresenceUpdate) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *SessionPresenceUpdate) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type PresenceSnapshot struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlayerId        string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SessionId       string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	State           string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	RealmId         string                 `protobuf:"bytes,4,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	Location        string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	LastHeartbeatAt string                 `protobuf:"bytes,6,opt,name=last_heartbeat_at,json=lastHeartbeatAt,proto3" json:"last_heartbeat_at,omitempty"`
	LastSeenAt      string                 `protobuf:"bytes,7,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	ConnectedAt     string                 `protobuf:"bytes,8,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	DisconnectedAt  string                 `protobuf:"bytes,9,opt,name=disconnected_at,json=disconnectedAt,proto3" json:"disconnected_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PresenceSnapshot) Reset() {
	*x = PresenceSnapshot{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceSnapshot) ProtoMessage() {}

func (x *PresenceSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceSnapshot.ProtoReflect.Descriptor instead.
func (*PresenceSnapshot) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *PresenceSnapshot) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PresenceSnapshot) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PresenceSnapshot) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PresenceSnapshot) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *PresenceSnapshot) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *PresenceSnapshot) GetLastHeartbeatAt() string {
	if x != nil {
		return x.LastHeartbeatAt
	}
	return ""
}

func (x *PresenceSnapshot) GetLastSeenAt() string {
	if x != nil {
		return x.LastSeenAt
	}
	return ""
}

func (x *PresenceSnapshot) GetConnectedAt() string {
	if x != nil {
		return x.ConnectedAt
	}
	return ""
}

func (x *PresenceSnapshot) GetDisconnectedAt() string {
	if x != nil {
		return x.DisconnectedAt
	}
	return ""
}

type ResolveSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSessionRequest) Reset() {
	*x = ResolveSessionRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSessionRequest) ProtoMessage() {}

func (x *ResolveSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSessionRequest.ProtoReflect.Descriptor instead.
func (*ResolveSessionRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveSessionRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type RealtimeSession struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AccountId         string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	PlayerId          string                 `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	RealmId           string                 `protobuf:"bytes,4,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	Location          string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	ClientVersion     string                 `protobuf:"bytes,6,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	State             string                 `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	PresenceState     string                 `protobuf:"bytes,8,opt,name=presence_state,json=presenceState,proto3" json:"presence_state,omitempty"`
	LastServerEventId string                 `protobuf:"bytes,9,opt,name=last_server_event_id,json=lastServerEventId,proto3" json:"last_server_event_id,omitempty"`
	ConnectedAt       string                 `protobuf:"bytes,10,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	LastHeartbeatAt   string                 `protobuf:"bytes,11,opt,name=last_heartbeat_at,json=lastHeartbeatAt,proto3" json:"last_heartbeat_at,omitempty"`
	DisconnectedAt    string                 `protobuf:"bytes,12,opt,name=disconnected_at,json=disconnectedAt,proto3" json:"disconnected_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RealtimeSession) Reset() {
	*x = RealtimeSession{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealtimeSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeSession) ProtoMessage() {}

func (x *RealtimeSession) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeSession.ProtoReflect.Descriptor instead.
func (*RealtimeSession) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *RealtimeSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RealtimeSession) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RealtimeSession) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *RealtimeSession) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *RealtimeSession) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *RealtimeSession) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *RealtimeSession) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *RealtimeSession) GetPresenceState() string {
	if x != nil {
		return x.PresenceState
	}
	return ""
}

func (x *RealtimeSession) GetLastServerEventId() string {
	if x != nil {
		return x.LastServerEventId
	}
	return ""
}

func (x *RealtimeSession) GetConnectedAt() string {
	if x != nil {
		return x.ConnectedAt
	}
	return ""
}

func (x *RealtimeSession) GetLastHeartbeatAt() string {
	if x != nil {
		return x.LastHeartbeatAt
	}
	return ""
}

func (x *RealtimeSession) GetDisconnectedAt() string {
	if x != nil {
		return x.DisconnectedAt
	}
	return ""
}

type HandshakeRealtimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RealmId       string                 `protobuf:"bytes,3,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	ClientVersion string                 `protobuf:"bytes,5,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRealtimeRequest) Reset() {
	*x = HandshakeRealtimeRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRealtimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRealtimeRequest) ProtoMessage() {}

func (x *HandshakeRealtimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRealtimeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRealtimeRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *HandshakeRealtimeRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *HandshakeRealtimeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HandshakeRealtimeRequest) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *HandshakeRealtimeRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *HandshakeRealtimeRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

type ResumeRealtimeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AccessToken       string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	SessionId         string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	LastServerEventId string                 `protobuf:"bytes,3,opt,name=last_server_event_id,json=lastServerEventId,proto3" json:"last_server_event_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResumeRealtimeRequest) Reset() {
	*x = ResumeRealtimeRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRealtimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRealtimeRequest) ProtoMessage() {}

func (x *ResumeRealtimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRealtimeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRealtimeRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *ResumeRealtimeRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ResumeRealtimeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResumeRealtimeRequest) GetLastServerEventId() string {
	if x != nil {
		return x.LastServerEventId
	}
	return ""
}

type RealtimeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealtimeSessionRequest) Reset() {
	*x = RealtimeSessionRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealtimeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeSessionRequest) ProtoMessage() {}

func (x *RealtimeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeSessionRequest.ProtoReflect.Descriptor instead.
func (*RealtimeSessionRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *RealtimeSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ChatDeliveryTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Presence      string                 `protobuf:"bytes,2,opt,name=presence,proto3" json:"presence,omitempty"`
	DeliveryMode  string                 `protobuf:"bytes,3,opt,name=delivery_mode,json=deliveryMode,proto3" json:"delivery_mode,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RealmId       string                 `protobuf:"bytes,5,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatDeliveryTarget) Reset() {
	*x = ChatDeliveryTarget{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatDeliveryTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatDeliveryTarget) ProtoMessage() {}

func (x *ChatDeliveryTarget) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatDeliveryTarget.ProtoReflect.Descriptor instead.
func (*ChatDeliveryTarget) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *ChatDeliveryTarget) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ChatDeliveryTarget) GetPresence() string {
	if x != nil {
		return x.Presence
	}
	return ""
}

func (x *ChatDeliveryTarget) GetDeliveryMode() string {
	if x != nil {
		return x.DeliveryMode
	}
	return ""
}

func (x *ChatDeliveryTarget) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatDeliveryTarget) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *ChatDeliveryTarget) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type ChatMessageEnvelope struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventId        string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Stream         string                 `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	Kind           string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	ConversationId string                 `protobuf:"bytes,4,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	MessageId      string                 `protobuf:"bytes,5,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Seq            int64                  `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`
	SenderPlayerId string                 `protobuf:"bytes,7,opt,name=sender_player_id,json=senderPlayerId,proto3" json:"sender_player_id,omitempty"`
	Body           string                 `protobuf:"bytes,8,opt,name=body,proto3" json:"body,omitempty"`
	SentAt         string                 `protobuf:"bytes,9,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatMessageEnvelope) Reset() {
	*x = ChatMessageEnvelope{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessageEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageEnvelope) ProtoMessage() {}

func (x *ChatMessageEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageEnvelope.ProtoReflect.Descriptor instead.
func (*ChatMessageEnvelope) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *ChatMessageEnvelope) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ChatMessageEnvelope) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *ChatMessageEnvelope) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ChatMessageEnvelope) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatMessageEnvelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatMessageEnvelope) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ChatMessageEnvelope) GetSenderPlayerId() string {
	if x != nil {
		return x.SenderPlayerId
	}
	return ""
}

func (x *ChatMessageEnvelope) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ChatMessageEnvelope) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

type SessionEventInbox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Events        []*ChatMessageEnvelope `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEventInbox) Reset() {
	*x = SessionEventInbox{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEventInbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEventInbox) ProtoMessage() {}

func (x *SessionEventInbox) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEventInbox.ProtoReflect.Descriptor instead.
func (*SessionEventInbox) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *SessionEventInbox) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionEventInbox) GetEvents() []*ChatMessageEnvelope {
	if x != nil {
		return x.Events
	}
	return nil
}

type DispatchChatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderPlayerId string                 `protobuf:"bytes,2,opt,name=sender_player_id,json=senderPlayerId,proto3" json:"sender_player_id,omitempty"`
	MessageId      string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Seq            int64                  `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	Body           string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	SentAt         string                 `protobuf:"bytes,6,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DispatchChatRequest) Reset() {
	*x = DispatchChatRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchChatRequest) ProtoMessage() {}

func (x *DispatchChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchChatRequest.ProtoReflect.Descriptor instead.
func (*DispatchChatRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *DispatchChatRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *DispatchChatRequest) GetSenderPlayerId() string {
	if x != nil {
		return x.SenderPlayerId
	}
	return ""
}

func (x *DispatchChatRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DispatchChatRequest) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *DispatchChatRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *DispatchChatRequest) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

type DispatchChatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	MessageId      string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	PushedCount    int32                  `protobuf:"varint,3,opt,name=pushed_count,json=pushedCount,proto3" json:"pushed_count,omitempty"`
	DeferredCount  int32                  `protobuf:"varint,4,opt,name=deferred_count,json=deferredCount,proto3" json:"deferred_count,omitempty"`
	PushedSessions []string               `protobuf:"bytes,5,rep,name=pushed_sessions,json=pushedSessions,proto3" json:"pushed_sessions,omitempty"`
	Deferred       []*ChatDeliveryTarget  `protobuf:"bytes,6,rep,name=deferred,proto3" json:"deferred,omitempty"`
	Targets        []*ChatDeliveryTarget  `protobuf:"bytes,7,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DispatchChatResponse) Reset() {
	*x = DispatchChatResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchChatResponse) ProtoMessage() {}

func (x *DispatchChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchChatResponse.ProtoReflect.Descriptor instead.
func (*DispatchChatResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *DispatchChatResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *DispatchChatResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DispatchChatResponse) GetPushedCount() int32 {
	if x != nil {
		return x.PushedCount
	}
	return 0
}

func (x *DispatchChatResponse) GetDeferredCount() int32 {
	if x != nil {
		return x.DeferredCount
	}
	return 0
}

func (x *DispatchChatResponse) GetPushedSessions() []string {
	if x != nil {
		return x.PushedSessions
	}
	return nil
}

func (x *DispatchChatResponse) GetDeferred() []*ChatDeliveryTarget {
	if x != nil {
		return x.Deferred
	}
	return nil
}

func (x *DispatchChatResponse) GetTargets() []*ChatDeliveryTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

type AckConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	AckSeq         int64                  `protobuf:"varint,3,opt,name=ack_seq,json=ackSeq,proto3" json:"ack_seq,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AckConversationRequest) Reset() {
	*x = AckConversationRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckConversationRequest) ProtoMessage() {}

func (x *AckConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckConversationRequest.ProtoReflect.Descriptor instead.
func (*AckConversationRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *AckConversationRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AckConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *AckConversationRequest) GetAckSeq() int64 {
	if x != nil {
		return x.AckSeq
	}
	return 0
}

type AckConversationResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConversationId   string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	AckSeq           int64                  `protobuf:"varint,3,opt,name=ack_seq,json=ackSeq,proto3" json:"ack_seq,omitempty"`
	PrunedCount      int32                  `protobuf:"varint,4,opt,name=pruned_count,json=prunedCount,proto3" json:"pruned_count,omitempty"`
	LastAckedEventId string                 `protobuf:"bytes,5,opt,name=last_acked_event_id,json=lastAckedEventId,proto3" json:"last_acked_event_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AckConversationResponse) Reset() {
	*x = AckConversationResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckConversationResponse) ProtoMessage() {}

func (x *AckConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckConversationResponse.ProtoReflect.Descriptor instead.
func (*AckConversationResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{14}
}

func (x *AckConversationResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AckConversationResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *AckConversationResponse) GetAckSeq() int64 {
	if x != nil {
		return x.AckSeq
	}
	return 0
}

func (x *AckConversationResponse) GetPrunedCount() int32 {
	if x != nil {
		return x.PrunedCount
	}
	return 0
}

func (x *AckConversationResponse) GetLastAckedEventId() string {
	if x != nil {
		return x.LastAckedEventId
	}
	return ""
}

type ReplayMessagesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	AfterSeq       int64                  `protobuf:"varint,3,opt,name=after_seq,json=afterSeq,proto3" json:"after_seq,omitempty"`
	Limit          int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReplayMessagesRequest) Reset() {
	*x = ReplayMessagesRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayMessagesRequest) ProtoMessage() {}

func (x *ReplayMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayMessagesRequest.ProtoReflect.Descriptor instead.
func (*ReplayMessagesRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{15}
}

func (x *ReplayMessagesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReplayMessagesRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ReplayMessagesRequest) GetAfterSeq() int64 {
	if x != nil {
		return x.AfterSeq
	}
	return 0
}

func (x *ReplayMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ChatReplayMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Seq            int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	SenderPlayerId string                 `protobuf:"bytes,4,opt,name=sender_player_id,json=senderPlayerId,proto3" json:"sender_player_id,omitempty"`
	Body           string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatReplayMessage) Reset() {
	*x = ChatReplayMessage{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReplayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReplayMessage) ProtoMessage() {}

func (x *ChatReplayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReplayMessage.ProtoReflect.Descriptor instead.
func (*ChatReplayMessage) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{16}
}

func (x *ChatReplayMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatReplayMessage) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatReplayMessage) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ChatReplayMessage) GetSenderPlayerId() string {
	if x != nil {
		return x.SenderPlayerId
	}
	return ""
}

func (x *ChatReplayMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ChatReplayMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ReplayMessagesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	PlayerId       string                 `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	AfterSeq       int64                  `protobuf:"varint,4,opt,name=after_seq,json=afterSeq,proto3" json:"after_seq,omitempty"`
	Messages       []*ChatReplayMessage   `protobuf:"bytes,5,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReplayMessagesResponse) Reset() {
	*x = ReplayMessagesResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayMessagesResponse) ProtoMessage() {}

func (x *ReplayMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayMessagesResponse.ProtoReflect.Descriptor instead.
func (*ReplayMessagesResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{17}
}

func (x *ReplayMessagesResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReplayMessagesResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ReplayMessagesResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ReplayMessagesResponse) GetAfterSeq() int64 {
	if x != nil {
		return x.AfterSeq
	}
	return 0
}

func (x *ReplayMessagesResponse) GetMessages() []*ChatReplayMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x18gateway/v1/gateway.proto\x12\x19social_backend.gateway.v1\"E\n" +
	"\aSubject\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"\x90\x01\n" +
	"\x15SessionPresenceUpdate\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x19\n" +
	"\brealm_id\x18\x03 \x01(\tR\arealmId\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\"\xb5\x02\n" +
	"\x10PresenceSnapshot\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x19\n" +
	"\brealm_id\x18\x04 \x01(\tR\arealmId\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12*\n" +
	"\x11last_heartbeat_at\x18\x06 \x01(\tR\x0flastHeartbeatAt\x12 \n" +
	"\flast_seen_at\x18\a \x01(\tR\n" +
	"lastSeenAt\x12!\n" +
	"\fconnected_at\x18\b \x01(\tR\vconnectedAt\x12'\n" +
	"\x0fdisconnected_at\x18\t \x01(\tR\x0edisconnectedAt\":\n" +
	"\x15ResolveSessionRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\xb0\x03\n" +
	"\x0fRealtimeSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\tR\bplayerId\x12\x19\n" +
	"\brealm_id\x18\x04 \x01(\tR\arealmId\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12%\n" +
	"\x0eclient_version\x18\x06 \x01(\tR\rclientVersion\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\x12%\n" +
	"\x0epresence_state\x18\b \x01(\tR\rpresenceState\x12/\n" +
	"\x14last_server_event_id\x18\t \x01(\tR\x11lastServerEventId\x12!\n" +
	"\fconnected_at\x18\n" +
	" \x01(\tR\vconnectedAt\x12*\n" +
	"\x11last_heartbeat_at\x18\v \x01(\tR\x0flastHeartbeatAt\x12'\n" +
	"\x0fdisconnected_at\x18\f \x01(\tR\x0edisconnectedAt\"\xba\x01\n" +
	"\x18HandshakeRealtimeRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x19\n" +
	"\brealm_id\x18\x03 \x01(\tR\arealmId\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12%\n" +
	"\x0eclient_version\x18\x05 \x01(\tR\rclientVersion\"\x8a\x01\n" +
	"\x15ResumeRealtimeRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12/\n" +
	"\x14last_server_event_id\x18\x03 \x01(\tR\x11lastServerEventId\"7\n" +
	"\x16RealtimeSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xc8\x01\n" +
	"\x12ChatDeliveryTarget\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1a\n" +
	"\bpresence\x18\x02 \x01(\tR\bpresence\x12#\n" +
	"\rdelivery_mode\x18\x03 \x01(\tR\fdeliveryMode\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x19\n" +
	"\brealm_id\x18\x05 \x01(\tR\arealmId\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\"\x8d\x02\n" +
	"\x13ChatMessageEnvelope\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12'\n" +
	"\x0fconversation_id\x18\x04 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x05 \x01(\tR\tmessageId\x12\x10\n" +
	"\x03seq\x18\x06 \x01(\x03R\x03seq\x12(\n" +
	"\x10sender_player_id\x18\a \x01(\tR\x0esenderPlayerId\x12\x12\n" +
	"\x04body\x18\b \x01(\tR\x04body\x12\x17\n" +
	"\asent_at\x18\t \x01(\tR\x06sentAt\"z\n" +
	"\x11SessionEventInbox\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12F\n" +
	"\x06events\x18\x02 \x03(\v2..social_backend.gateway.v1.ChatMessageEnvelopeR\x06events\"\xc6\x01\n" +
	"\x13DispatchChatRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12(\n" +
	"\x10sender_player_id\x18\x02 \x01(\tR\x0esenderPlayerId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x03R\x03seq\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x17\n" +
	"\asent_at\x18\x06 \x01(\tR\x06sentAt\"\xe5\x02\n" +
	"\x14DispatchChatResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12!\n" +
	"\fpushed_count\x18\x03 \x01(\x05R\vpushedCount\x12%\n" +
	"\x0edeferred_count\x18\x04 \x01(\x05R\rdeferredCount\x12'\n" +
	"\x0fpushed_sessions\x18\x05 \x03(\tR\x0epushedSessions\x12I\n" +
	"\bdeferred\x18\x06 \x03(\v2-.social_backend.gateway.v1.ChatDeliveryTargetR\bdeferred\x12G\n" +
	"\atargets\x18\a \x03(\v2-.social_backend.gateway.v1.ChatDeliveryTargetR\atargets\"y\n" +
	"\x16AckConversationRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x17\n" +
	"\aack_seq\x18\x03 \x01(\x03R\x06ackSeq\"\xcc\x01\n" +
	"\x17AckConversationResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x17\n" +
	"\aack_seq\x18\x03 \x01(\x03R\x06ackSeq\x12!\n" +
	"\fpruned_count\x18\x04 \x01(\x05R\vprunedCount\x12-\n" +
	"\x13last_acked_event_id\x18\x05 \x01(\tR\x10lastAckedEventId\"\x92\x01\n" +
	"\x15ReplayMessagesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tafter_seq\x18\x03 \x01(\x03R\bafterSeq\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xbb\x01\n" +
	"\x11ChatReplayMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\x12(\n" +
	"\x10sender_player_id\x18\x04 \x01(\tR\x0esenderPlayerId\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\xe4\x01\n" +
	"\x16ReplayMessagesResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\tR\bplayerId\x12\x1b\n" +
	"\tafter_seq\x18\x04 \x01(\x03R\bafterSeq\x12H\n" +
	"\bmessages\x18\x05 \x03(\v2,.social_backend.gateway.v1.ChatReplayMessageR\bmessages2\xf1\v\n" +
	"\x0eGatewayService\x12f\n" +
	"\x0eResolveSession\x120.social_backend.gateway.v1.ResolveSessionRequest\x1a\".social_backend.gateway.v1.Subject\x12p\n" +
	"\x0fConnectPresence\x120.social_backend.gateway.v1.SessionPresenceUpdate\x1a+.social_backend.gateway.v1.PresenceSnapshot\x12r\n" +
	"\x11HeartbeatPresence\x120.social_backend.gateway.v1.SessionPresenceUpdate\x1a+.social_backend.gateway.v1.PresenceSnapshot\x12s\n" +
	"\x12DisconnectPresence\x120.social_backend.gateway.v1.SessionPresenceUpdate\x1a+.social_backend.gateway.v1.PresenceSnapshot\x12t\n" +
	"\x11HandshakeRealtime\x123.social_backend.gateway.v1.HandshakeRealtimeRequest\x1a*.social_backend.gateway.v1.RealtimeSession\x12n\n" +
	"\x0eResumeRealtime\x120.social_backend.gateway.v1.ResumeRealtimeRequest\x1a*.social_backend.gateway.v1.RealtimeSession\x12r\n" +
	"\x11HeartbeatRealtime\x121.social_backend.gateway.v1.RealtimeSessionRequest\x1a*.social_backend.gateway.v1.RealtimeSession\x12n\n" +
	"\rCloseRealtime\x121.social_backend.gateway.v1.RealtimeSessionRequest\x1a*.social_backend.gateway.v1.RealtimeSession\x12s\n" +
	"\x12GetRealtimeSession\x121.social_backend.gateway.v1.RealtimeSessionRequest\x1a*.social_backend.gateway.v1.RealtimeSession\x12{\n" +
	"\x18GetRealtimeSessionEvents\x121.social_backend.gateway.v1.RealtimeSessionRequest\x1a,.social_backend.gateway.v1.SessionEventInbox\x12o\n" +
	"\fDispatchChat\x12..social_backend.gateway.v1.DispatchChatRequest\x1a/.social_backend.gateway.v1.DispatchChatResponse\x12x\n" +
	"\x0fAckConversation\x121.social_backend.gateway.v1.AckConversationRequest\x1a2.social_backend.gateway.v1.AckConversationResponse\x12u\n" +
	"\x0eReplayMessages\x120.social_backend.gateway.v1.ReplayMessagesRequest\x1a1.social_backend.gateway.v1.ReplayMessagesResponseB\xf2\x01\n" +
	"\x1dcom.social_backend.gateway.v1B\fGatewayProtoP\x01ZAgithub.com/xyun1996/social_backend/api/proto/gateway/v1;gatewayv1\xa2\x02\x03SGX\xaa\x02\x18SocialBackend.Gateway.V1\xca\x02\x18SocialBackend\\Gateway\\V1\xe2\x02$SocialBackend\\Gateway\\V1\\GPBMetadata\xea\x02\x1aSocialBackend::Gateway::V1b\x06proto3"

var (
	file_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_gateway_v1_gateway_proto_rawDescData []byte
)

func file_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_gateway_v1_gateway_proto_rawDescData
}

var file_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_gateway_v1_gateway_proto_goTypes = []any{
	(*Subject)(nil),                  // 0: social_backend.gateway.v1.Subject
	(*SessionPresenceUpdate)(nil),    // 1: social_backend.gateway.v1.SessionPresenceUpdate
	(*PresenceSnapshot)(nil),         // 2: social_backend.gateway.v1.PresenceSnapshot
	(*ResolveSessionRequest)(nil),    // 3: social_backend.gateway.v1.ResolveSessionRequest
	(*RealtimeSession)(nil),          // 4: social_backend.gateway.v1.RealtimeSession
	(*HandshakeRealtimeRequest)(nil), // 5: social_backend.gateway.v1.HandshakeRealtimeRequest
	(*ResumeRealtimeRequest)(nil),    // 6: social_backend.gateway.v1.ResumeRealtimeRequest
	(*RealtimeSessionRequest)(nil),   // 7: social_backend.gateway.v1.RealtimeSessionRequest
	(*ChatDeliveryTarget)(nil),       // 8: social_backend.gateway.v1.ChatDeliveryTarget
	(*ChatMessageEnvelope)(nil),      // 9: social_backend.gateway.v1.ChatMessageEnvelope
	(*SessionEventInbox)(nil),        // 10: social_backend.gateway.v1.SessionEventInbox
	(*DispatchChatRequest)(nil),      // 11: social_backend.gateway.v1.DispatchChatRequest
	(*DispatchChatResponse)(nil),     // 12: social_backend.gateway.v1.DispatchChatResponse
	(*AckConversationRequest)(nil),   // 13: social_backend.gateway.v1.AckConversationRequest
	(*AckConversationResponse)(nil),  // 14: social_backend.gateway.v1.AckConversationResponse
	(*ReplayMessagesRequest)(nil),    // 15: social_backend.gateway.v1.ReplayMessagesRequest
	(*ChatReplayMessage)(nil),        // 16: social_backend.gateway.v1.ChatReplayMessage
	(*ReplayMessagesResponse)(nil),   // 17: social_backend.gateway.v1.ReplayMessagesResponse
}
var file_gateway_v1_gateway_proto_depIdxs = []int32{
	9,  // 0: social_backend.gateway.v1.SessionEventInbox.events:type_name -> social_backend.gateway.v1.ChatMessageEnvelope
	8,  // 1: social_backend.gateway.v1.DispatchChatResponse.deferred:type_name -> social_backend.gateway.v1.ChatDeliveryTarget
	8,  // 2: social_backend.gateway.v1.DispatchChatResponse.targets:type_name -> social_backend.gateway.v1.ChatDeliveryTarget
	16, // 3: social_backend.gateway.v1.ReplayMessagesResponse.messages:type_name -> social_backend.gateway.v1.ChatReplayMessage
	3,  // 4: social_backend.gateway.v1.GatewayService.ResolveSession:input_type -> social_backend.gateway.v1.ResolveSessionRequest
	1,  // 5: social_backend.gateway.v1.GatewayService.ConnectPresence:input_type -> social_backend.gateway.v1.SessionPresenceUpdate
	1,  // 6: social_backend.gateway.v1.GatewayService.HeartbeatPresence:input_type -> social_backend.gateway.v1.SessionPresenceUpdate
	1,  // 7: social_backend.gateway.v1.GatewayService.DisconnectPresence:input_type -> social_backend.gateway.v1.SessionPresenceUpdate
	5,  // 8: social_backend.gateway.v1.GatewayService.HandshakeRealtime:input_type -> social_backend.gateway.v1.HandshakeRealtimeRequest
	6,  // 9: social_backend.gateway.v1.GatewayService.ResumeRealtime:input_type -> social_backend.gateway.v1.ResumeRealtimeRequest
	7,  // 10: social_backend.gateway.v1.GatewayService.HeartbeatRealtime:input_type -> social_backend.gateway.v1.RealtimeSessionRequest
	7,  // 11: social_backend.gateway.v1.GatewayService.CloseRealtime:input_type -> social_backend.gateway.v1.RealtimeSessionRequest
	7,  // 12: social_backend.gateway.v1.GatewayService.GetRealtimeSession:input_type -> social_backend.gateway.v1.RealtimeSessionRequest
	7,  // 13: social_backend.gateway.v1.GatewayService.GetRealtimeSessionEvents:input_type -> social_backend.gateway.v1.RealtimeSessionRequest
	11, // 14: social_backend.gateway.v1.GatewayService.DispatchChat:input_type -> social_backend.gateway.v1.DispatchChatRequest
	13, // 15: social_backend.gateway.v1.GatewayService.AckConversation:input_type -> social_backend.gateway.v1.AckConversationRequest
	15, // 16: social_backend.gateway.v1.GatewayService.ReplayMessages:input_type -> social_backend.gateway.v1.ReplayMessagesRequest
	0,  // 17: social_backend.gateway.v1.GatewayService.ResolveSession:output_type -> social_backend.gateway.v1.Subject
	2,  // 18: social_backend.gateway.v1.GatewayService.ConnectPresence:output_type -> social_backend.gateway.v1.PresenceSnapshot
	2,  // 19: social_backend.gateway.v1.GatewayService.HeartbeatPresence:output_type -> social_backend.gateway.v1.PresenceSnapshot
	2,  // 20: social_backend.gateway.v1.GatewayService.DisconnectPresence:output_type -> social_backend.gateway.v1.PresenceSnapshot
	4,  // 21: social_backend.gateway.v1.GatewayService.HandshakeRealtime:output_type -> social_backend.gateway.v1.RealtimeSession
	4,  // 22: social_backend.gateway.v1.GatewayService.ResumeRealtime:output_type -> social_backend.gateway.v1.RealtimeSession
	4,  // 23: social_backend.gateway.v1.GatewayService.HeartbeatRealtime:output_type -> social_backend.gateway.v1.RealtimeSession
	4,  // 24: social_backend.gateway.v1.GatewayService.CloseRealtime:output_type -> social_backend.gateway.v1.RealtimeSession
	4,  // 25: social_backend.gateway.v1.GatewayService.GetRealtimeSession:output_type -> social_backend.gateway.v1.RealtimeSession
	10, // 26: social_backend.gateway.v1.GatewayService.GetRealtimeSessionEvents:output_type -> social_backend.gateway.v1.SessionEventInbox
	12, // 27: social_backend.gateway.v1.GatewayService.DispatchChat:output_type -> social_backend.gateway.v1.DispatchChatResponse
	14, // 28: social_backend.gateway.v1.GatewayService.AckConversation:output_type -> social_backend.gateway.v1.AckConversationResponse
	17, // 29: social_backend.gateway.v1.GatewayService.ReplayMessages:output_type -> social_backend.gateway.v1.ReplayMessagesResponse
	17, // [17:30] is the sub-list for method output_type
	4,  // [4:17] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_gateway_v1_gateway_proto_init() }
func file_gateway_v1_gateway_proto_init() {
	if File_gateway_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_v1_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_gateway_v1_gateway_proto = out.File
	file_gateway_v1_gateway_proto_goTypes = nil
	file_gateway_v1_gateway_proto_depIdxs = nil
}
