// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: presence.proto

package presencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Presence struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlayerId        string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	SessionId       string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RealmId         string                 `protobuf:"bytes,4,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	Location        string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	LastHeartbeatAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_heartbeat_at,json=lastHeartbeatAt,proto3" json:"last_heartbeat_at,omitempty"`
	LastSeenAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	ConnectedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	DisconnectedAt  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=disconnected_at,json=disconnectedAt,proto3" json:"disconnected_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Presence) Reset() {
	*x = Presence{}
	mi := &file_presence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Presence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Presence) ProtoMessage() {}

func (x *Presence) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Presence.ProtoReflect.Descriptor instead.
func (*Presence) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{0}
}

func (x *Presence) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Presence) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Presence) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Presence) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *Presence) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Presence) GetLastHeartbeatAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeatAt
	}
	return nil
}

func (x *Presence) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

func (x *Presence) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

func (x *Presence) GetDisconnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DisconnectedAt
	}
	return nil
}

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RealmId       string                 `protobuf:"bytes,3,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_presence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ConnectRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConnectRequest) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *ConnectRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RealmId       string                 `protobuf:"bytes,3,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_presence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HeartbeatRequest) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *HeartbeatRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_presence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{3}
}

func (x *DisconnectRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *DisconnectRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceRequest) Reset() {
	*x = GetPresenceRequest{}
	mi := &file_presence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceRequest) ProtoMessage() {}

func (x *GetPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceRequest.ProtoReflect.Descriptor instead.
func (*GetPresenceRequest) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{4}
}

func (x *GetPresenceRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

var File_presence_proto protoreflect.FileDescriptor

const file_presence_proto_rawDesc = "" +
	"\n" +
	"\x0epresence.proto\x12\x1asocial_backend.presence.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x03\n" +
	"\bPresence\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x19\n" +
	"\brealm_id\x18\x04 \x01(\tR\arealmId\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12F\n" +
	"\x11last_heartbeat_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastHeartbeatAt\x12<\n" +
	"\flast_seen_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\x12=\n" +
	"\fconnected_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\x12C\n" +
	"\x0fdisconnected_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0edisconnectedAt\"\x83\x01\n" +
	"\x0eConnectRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x19\n" +
	"\brealm_id\x18\x03 \x01(\tR\arealmId\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\"\x85\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x19\n" +
	"\brealm_id\x18\x03 \x01(\tR\arealmId\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\"O\n" +
	"\x11DisconnectRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"1\n" +
	"\x12GetPresenceRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId2\x97\x03\n" +
	"\x0fPresenceService\x12[\n" +
	"\aConnect\x12*.social_backend.presence.v1.ConnectRequest\x1a$.social_backend.presence.v1.Presence\x12_\n" +
	"\tHeartbeat\x12,.social_backend.presence.v1.HeartbeatRequest\x1a$.social_backend.presence.v1.Presence\x12a\n" +
	"\n" +
	"Disconnect\x12-.social_backend.presence.v1.DisconnectRequest\x1a$.social_backend.presence.v1.Presence\x12c\n" +
	"\vGetPresence\x12..social_backend.presence.v1.GetPresenceRequest\x1a$.social_backend.presence.v1.PresenceB\xfa\x01\n" +
	"\x1ecom.social_backend.presence.v1B\rPresenceProtoP\x01ZCgithub.com/xyun1996/social_backend/api/proto/presence/v1;presencev1\xa2\x02\x03SPX\xaa\x02\x19SocialBackend.Presence.V1\xca\x02\x19SocialBackend\\Presence\\V1\xe2\x02%SocialBackend\\Presence\\V1\\GPBMetadata\xea\x02\x1bSocialBackend::Presence::V1b\x06proto3"

var (
	file_presence_proto_rawDescOnce sync.Once
	file_presence_proto_rawDescData []byte
)

func file_presence_proto_rawDescGZIP() []byte {
	file_presence_proto_rawDescOnce.Do(func() {
		file_presence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_presence_proto_rawDesc), len(file_presence_proto_rawDesc)))
	})
	return file_presence_proto_rawDescData
}

var file_presence_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_presence_proto_goTypes = []any{
	(*Presence)(nil),              // 0: social_backend.presence.v1.Presence
	(*ConnectRequest)(nil),        // 1: social_backend.presence.v1.ConnectRequest
	(*HeartbeatRequest)(nil),      // 2: social_backend.presence.v1.HeartbeatRequest
	(*DisconnectRequest)(nil),     // 3: social_backend.presence.v1.DisconnectRequest
	(*GetPresenceRequest)(nil),    // 4: social_backend.presence.v1.GetPresenceRequest
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_presence_proto_depIdxs = []int32{
	5, // 0: social_backend.presence.v1.Presence.last_heartbeat_at:type_name -> google.protobuf.Timestamp
	5, // 1: social_backend.presence.v1.Presence.last_seen_at:type_name -> google.protobuf.Timestamp
	5, // 2: social_backend.presence.v1.Presence.connected_at:type_name -> google.protobuf.Timestamp
	5, // 3: social_backend.presence.v1.Presence.disconnected_at:type_name -> google.protobuf.Timestamp
	1, // 4: social_backend.presence.v1.PresenceService.Connect:input_type -> social_backend.presence.v1.ConnectRequest
	2, // 5: social_backend.presence.v1.PresenceService.Heartbeat:input_type -> social_backend.presence.v1.HeartbeatRequest
	3, // 6: social_backend.presence.v1.PresenceService.Disconnect:input_type -> social_backend.presence.v1.DisconnectRequest
	4, // 7: social_backend.presence.v1.PresenceService.GetPresence:input_type -> social_backend.presence.v1.GetPresenceRequest
	0, // 8: social_backend.presence.v1.PresenceService.Connect:output_type -> social_backend.presence.v1.Presence
	0, // 9: social_backend.presence.v1.PresenceService.Heartbeat:output_type -> social_backend.presence.v1.Presence
	0, // 10: social_backend.presence.v1.PresenceService.Disconnect:output_type -> social_backend.presence.v1.Presence
	0, // 11: social_backend.presence.v1.PresenceService.GetPresence:output_type -> social_backend.presence.v1.Presence
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_presence_proto_init() }
func file_presence_proto_init() {
	if File_presence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_presence_proto_rawDesc), len(file_presence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_presence_proto_goTypes,
		DependencyIndexes: file_presence_proto_depIdxs,
		MessageInfos:      file_presence_proto_msgTypes,
	}.Build()
	File_presence_proto = out.File
	file_presence_proto_goTypes = nil
	file_presence_proto_depIdxs = nil
}
