// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chat.proto

package chatv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Conversation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind            string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	ResourceId      string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	MemberPlayerIds []string               `protobuf:"bytes,4,rep,name=member_player_ids,json=memberPlayerIds,proto3" json:"member_player_ids,omitempty"`
	LastSeq         int64                  `protobuf:"varint,5,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Conversation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Conversation) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Conversation) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *Conversation) GetMemberPlayerIds() []string {
	if x != nil {
		return x.MemberPlayerIds
	}
	return nil
}

func (x *Conversation) GetLastSeq() int64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *Conversation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Seq            int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	SenderPlayerId string                 `protobuf:"bytes,4,opt,name=sender_player_id,json=senderPlayerId,proto3" json:"sender_player_id,omitempty"`
	Body           string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *Message) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Message) GetSenderPlayerId() string {
	if x != nil {
		return x.SenderPlayerId
	}
	return ""
}

func (x *Message) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ReadCursor struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	PlayerId       string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	AckSeq         int64                  `protobuf:"varint,3,opt,name=ack_seq,json=ackSeq,proto3" json:"ack_seq,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadCursor) Reset() {
	*x = ReadCursor{}
	mi := &file_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCursor) ProtoMessage() {}

func (x *ReadCursor) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCursor.ProtoReflect.Descriptor instead.
func (*ReadCursor) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ReadCursor) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ReadCursor) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ReadCursor) GetAckSeq() int64 {
	if x != nil {
		return x.AckSeq
	}
	return 0
}

func (x *ReadCursor) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DeliveryTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Presence      string                 `protobuf:"bytes,2,opt,name=presence,proto3" json:"presence,omitempty"`
	DeliveryMode  string                 `protobuf:"bytes,3,opt,name=delivery_mode,json=deliveryMode,proto3" json:"delivery_mode,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RealmId       string                 `protobuf:"bytes,5,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryTarget) Reset() {
	*x = DeliveryTarget{}
	mi := &file_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryTarget) ProtoMessage() {}

func (x *DeliveryTarget) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryTarget.ProtoReflect.Descriptor instead.
func (*DeliveryTarget) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

func (x *DeliveryTarget) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *DeliveryTarget) GetPresence() string {
	if x != nil {
		return x.Presence
	}
	return ""
}

func (x *DeliveryTarget) GetDeliveryMode() string {
	if x != nil {
		return x.DeliveryMode
	}
	return ""
}

func (x *DeliveryTarget) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DeliveryTarget) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *DeliveryTarget) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type CreateConversationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Kind            string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	ResourceId      string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	MemberPlayerIds []string               `protobuf:"bytes,3,rep,name=member_player_ids,json=memberPlayerIds,proto3" json:"member_player_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateConversationRequest) Reset() {
	*x = CreateConversationRequest{}
	mi := &file_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationRequest) ProtoMessage() {}

func (x *CreateConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationRequest.ProtoReflect.Descriptor instead.
func (*CreateConversationRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

func (x *CreateConversationRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CreateConversationRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CreateConversationRequest) GetMemberPlayerIds() []string {
	if x != nil {
		return x.MemberPlayerIds
	}
	return nil
}

type ListConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsRequest) Reset() {
	*x = ListConversationsRequest{}
	mi := &file_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsRequest) ProtoMessage() {}

func (x *ListConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsRequest.ProtoReflect.Descriptor instead.
func (*ListConversationsRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{5}
}

func (x *ListConversationsRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type ListConversationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Conversations []*Conversation        `protobuf:"bytes,2,rep,name=conversations,proto3" json:"conversations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsResponse) Reset() {
	*x = ListConversationsResponse{}
	mi := &file_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsResponse) ProtoMessage() {}

func (x *ListConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsResponse.ProtoReflect.Descriptor instead.
func (*ListConversationsResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{6}
}

func (x *ListConversationsResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ListConversationsResponse) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

type SendMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderPlayerId string                 `protobuf:"bytes,2,opt,name=sender_player_id,json=senderPlayerId,proto3" json:"sender_player_id,omitempty"`
	Body           string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{7}
}

func (x *SendMessageRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SendMessageRequest) GetSenderPlayerId() string {
	if x != nil {
		return x.SenderPlayerId
	}
	return ""
}

func (x *SendMessageRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type ReplayMessagesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	PlayerId       string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	AfterSeq       int64                  `protobuf:"varint,3,opt,name=after_seq,json=afterSeq,proto3" json:"after_seq,omitempty"`
	Limit          int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReplayMessagesRequest) Reset() {
	*x = ReplayMessagesRequest{}
	mi := &file_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayMessagesRequest) ProtoMessage() {}

func (x *ReplayMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayMessagesRequest.ProtoReflect.Descriptor instead.
func (*ReplayMessagesRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{8}
}

func (x *ReplayMessagesRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ReplayMessagesRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ReplayMessagesRequest) GetAfterSeq() int64 {
	if x != nil {
		return x.AfterSeq
	}
	return 0
}

func (x *ReplayMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ReplayMessagesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	PlayerId       string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	AfterSeq       int64                  `protobuf:"varint,3,opt,name=after_seq,json=afterSeq,proto3" json:"after_seq,omitempty"`
	Messages       []*Message             `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReplayMessagesResponse) Reset() {
	*x = ReplayMessagesResponse{}
	mi := &file_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayMessagesResponse) ProtoMessage() {}

func (x *ReplayMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayMessagesResponse.ProtoReflect.Descriptor instead.
func (*ReplayMessagesResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{9}
}

func (x *ReplayMessagesResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ReplayMessagesResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ReplayMessagesResponse) GetAfterSeq() int64 {
	if x != nil {
		return x.AfterSeq
	}
	return 0
}

func (x *ReplayMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type AckConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	PlayerId       string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	AckSeq         int64                  `protobuf:"varint,3,opt,name=ack_seq,json=ackSeq,proto3" json:"ack_seq,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AckConversationRequest) Reset() {
	*x = AckConversationRequest{}
	mi := &file_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckConversationRequest) ProtoMessage() {}

func (x *AckConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckConversationRequest.ProtoReflect.Descriptor instead.
func (*AckConversationRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{10}
}

func (x *AckConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *AckConversationRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *AckConversationRequest) GetAckSeq() int64 {
	if x != nil {
		return x.AckSeq
	}
	return 0
}

type PlanDeliveryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderPlayerId string                 `protobuf:"bytes,2,opt,name=sender_player_id,json=senderPlayerId,proto3" json:"sender_player_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlanDeliveryRequest) Reset() {
	*x = PlanDeliveryRequest{}
	mi := &file_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanDeliveryRequest) ProtoMessage() {}

func (x *PlanDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanDeliveryRequest.ProtoReflect.Descriptor instead.
func (*PlanDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{11}
}

func (x *PlanDeliveryRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *PlanDeliveryRequest) GetSenderPlayerId() string {
	if x != nil {
		return x.SenderPlayerId
	}
	return ""
}

type PlanDeliveryResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderPlayerId string                 `protobuf:"bytes,2,opt,name=sender_player_id,json=senderPlayerId,proto3" json:"sender_player_id,omitempty"`
	Targets        []*DeliveryTarget      `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlanDeliveryResponse) Reset() {
	*x = PlanDeliveryResponse{}
	mi := &file_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanDeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanDeliveryResponse) ProtoMessage() {}

func (x *PlanDeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanDeliveryResponse.ProtoReflect.Descriptor instead.
func (*PlanDeliveryResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{12}
}

func (x *PlanDeliveryResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *PlanDeliveryResponse) GetSenderPlayerId() string {
	if x != nil {
		return x.SenderPlayerId
	}
	return ""
}

func (x *PlanDeliveryResponse) GetTargets() []*DeliveryTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12\x16social_backend.chat.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd5\x01\n" +
	"\fConversation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\x12*\n" +
	"\x11member_player_ids\x18\x04 \x03(\tR\x0fmemberPlayerIds\x12\x19\n" +
	"\blast_seq\x18\x05 \x01(\x03R\alastSeq\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xcd\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\x12(\n" +
	"\x10sender_player_id\x18\x04 \x01(\tR\x0esenderPlayerId\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa6\x01\n" +
	"\n" +
	"ReadCursor\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x17\n" +
	"\aack_seq\x18\x03 \x01(\x03R\x06ackSeq\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc4\x01\n" +
	"\x0eDeliveryTarget\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1a\n" +
	"\bpresence\x18\x02 \x01(\tR\bpresence\x12#\n" +
	"\rdelivery_mode\x18\x03 \x01(\tR\fdeliveryMode\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x19\n" +
	"\brealm_id\x18\x05 \x01(\tR\arealmId\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\"|\n" +
	"\x19CreateConversationRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12*\n" +
	"\x11member_player_ids\x18\x03 \x03(\tR\x0fmemberPlayerIds\"7\n" +
	"\x18ListConversationsRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"\x84\x01\n" +
	"\x19ListConversationsResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12J\n" +
	"\rconversations\x18\x02 \x03(\v2$.social_backend.chat.v1.ConversationR\rconversations\"{\n" +
	"\x12SendMessageRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12(\n" +
	"\x10sender_player_id\x18\x02 \x01(\tR\x0esenderPlayerId\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"\x90\x01\n" +
	"\x15ReplayMessagesRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x1b\n" +
	"\tafter_seq\x18\x03 \x01(\x03R\bafterSeq\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xb8\x01\n" +
	"\x16ReplayMessagesResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x1b\n" +
	"\tafter_seq\x18\x03 \x01(\x03R\bafterSeq\x12;\n" +
	"\bmessages\x18\x04 \x03(\v2\x1f.social_backend.chat.v1.MessageR\bmessages\"w\n" +
	"\x16AckConversationRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x17\n" +
	"\aack_seq\x18\x03 \x01(\x03R\x06ackSeq\"h\n" +
	"\x13PlanDeliveryRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12(\n" +
	"\x10sender_player_id\x18\x02 \x01(\tR\x0esenderPlayerId\"\xab\x01\n" +
	"\x14PlanDeliveryResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12(\n" +
	"\x10sender_player_id\x18\x02 \x01(\tR\x0esenderPlayerId\x12@\n" +
	"\atargets\x18\x03 \x03(\v2&.social_backend.chat.v1.DeliveryTargetR\atargets2\x95\x05\n" +
	"\vChatService\x12m\n" +
	"\x12CreateConversation\x121.social_backend.chat.v1.CreateConversationRequest\x1a$.social_backend.chat.v1.Conversation\x12x\n" +
	"\x11ListConversations\x120.social_backend.chat.v1.ListConversationsRequest\x1a1.social_backend.chat.v1.ListConversationsResponse\x12Z\n" +
	"\vSendMessage\x12*.social_backend.chat.v1.SendMessageRequest\x1a\x1f.social_backend.chat.v1.Message\x12o\n" +
	"\x0eReplayMessages\x12-.social_backend.chat.v1.ReplayMessagesRequest\x1a..social_backend.chat.v1.ReplayMessagesResponse\x12e\n" +
	"\x0fAckConversation\x12..social_backend.chat.v1.AckConversationRequest\x1a\".social_backend.chat.v1.ReadCursor\x12i\n" +
	"\fPlanDelivery\x12+.social_backend.chat.v1.PlanDeliveryRequest\x1a,.social_backend.chat.v1.PlanDeliveryResponseB\xda\x01\n" +
	"\x1acom.social_backend.chat.v1B\tChatProtoP\x01Z;github.com/xyun1996/social_backend/api/proto/chat/v1;chatv1\xa2\x02\x03SCX\xaa\x02\x15SocialBackend.Chat.V1\xca\x02\x15SocialBackend\\Chat\\V1\xe2\x02!SocialBackend\\Chat\\V1\\GPBMetadata\xea\x02\x17SocialBackend::Chat::V1b\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_chat_proto_goTypes = []any{
	(*Conversation)(nil),              // 0: social_backend.chat.v1.Conversation
	(*Message)(nil),                   // 1: social_backend.chat.v1.Message
	(*ReadCursor)(nil),                // 2: social_backend.chat.v1.ReadCursor
	(*DeliveryTarget)(nil),            // 3: social_backend.chat.v1.DeliveryTarget
	(*CreateConversationRequest)(nil), // 4: social_backend.chat.v1.CreateConversationRequest
	(*ListConversationsRequest)(nil),  // 5: social_backend.chat.v1.ListConversationsRequest
	(*ListConversationsResponse)(nil), // 6: social_backend.chat.v1.ListConversationsResponse
	(*SendMessageRequest)(nil),        // 7: social_backend.chat.v1.SendMessageRequest
	(*ReplayMessagesRequest)(nil),     // 8: social_backend.chat.v1.ReplayMessagesRequest
	(*ReplayMessagesResponse)(nil),    // 9: social_backend.chat.v1.ReplayMessagesResponse
	(*AckConversationRequest)(nil),    // 10: social_backend.chat.v1.AckConversationRequest
	(*PlanDeliveryRequest)(nil),       // 11: social_backend.chat.v1.PlanDeliveryRequest
	(*PlanDeliveryResponse)(nil),      // 12: social_backend.chat.v1.PlanDeliveryResponse
	(*timestamppb.Timestamp)(nil),     // 13: google.protobuf.Timestamp
}
var file_chat_proto_depIdxs = []int32{
	13, // 0: social_backend.chat.v1.Conversation.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: social_backend.chat.v1.Message.created_at:type_name -> google.protobuf.Timestamp
	13, // 2: social_backend.chat.v1.ReadCursor.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: social_backend.chat.v1.ListConversationsResponse.conversations:type_name -> social_backend.chat.v1.Conversation
	1,  // 4: social_backend.chat.v1.ReplayMessagesResponse.messages:type_name -> social_backend.chat.v1.Message
	3,  // 5: social_backend.chat.v1.PlanDeliveryResponse.targets:type_name -> social_backend.chat.v1.DeliveryTarget
	4,  // 6: social_backend.chat.v1.ChatService.CreateConversation:input_type -> social_backend.chat.v1.CreateConversationRequest
	5,  // 7: social_backend.chat.v1.ChatService.ListConversations:input_type -> social_backend.chat.v1.ListConversationsRequest
	7,  // 8: social_backend.chat.v1.ChatService.SendMessage:input_type -> social_backend.chat.v1.SendMessageRequest
	8,  // 9: social_backend.chat.v1.ChatService.ReplayMessages:input_type -> social_backend.chat.v1.ReplayMessagesRequest
	10, // 10: social_backend.chat.v1.ChatService.AckConversation:input_type -> social_backend.chat.v1.AckConversationRequest
	11, // 11: social_backend.chat.v1.ChatService.PlanDelivery:input_type -> social_backend.chat.v1.PlanDeliveryRequest
	0,  // 12: social_backend.chat.v1.ChatService.CreateConversation:output_type -> social_backend.chat.v1.Conversation
	6,  // 13: social_backend.chat.v1.ChatService.ListConversations:output_type -> social_backend.chat.v1.ListConversationsResponse
	1,  // 14: social_backend.chat.v1.ChatService.SendMessage:output_type -> social_backend.chat.v1.Message
	9,  // 15: social_backend.chat.v1.ChatService.ReplayMessages:output_type -> social_backend.chat.v1.ReplayMessagesResponse
	2,  // 16: social_backend.chat.v1.ChatService.AckConversation:output_type -> social_backend.chat.v1.ReadCursor
	12, // 17: social_backend.chat.v1.ChatService.PlanDelivery:output_type -> social_backend.chat.v1.PlanDeliveryResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
