// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: invite.proto

package invitev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InviteService_CreateInvite_FullMethodName  = "/social_backend.invite.v1.InviteService/CreateInvite"
	InviteService_GetInvite_FullMethodName     = "/social_backend.invite.v1.InviteService/GetInvite"
	InviteService_RespondInvite_FullMethodName = "/social_backend.invite.v1.InviteService/RespondInvite"
	InviteService_ListInvites_FullMethodName   = "/social_backend.invite.v1.InviteService/ListInvites"
)

// InviteServiceClient is the client API for InviteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InviteServiceClient interface {
	CreateInvite(ctx context.Context, in *CreateInviteRequest, opts ...grpc.CallOption) (*Invite, error)
	GetInvite(ctx context.Context, in *GetInviteRequest, opts ...grpc.CallOption) (*Invite, error)
	RespondInvite(ctx context.Context, in *RespondInviteRequest, opts ...grpc.CallOption) (*Invite, error)
	ListInvites(ctx context.Context, in *ListInvitesRequest, opts ...grpc.CallOption) (*ListInvitesResponse, error)
}

type inviteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInviteServiceClient(cc grpc.ClientConnInterface) InviteServiceClient {
	return &inviteServiceClient{cc}
}

func (c *inviteServiceClient) CreateInvite(ctx context.Context, in *CreateInviteRequest, opts ...grpc.CallOption) (*Invite, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Invite)
	err := c.cc.Invoke(ctx, InviteService_CreateInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inviteServiceClient) GetInvite(ctx context.Context, in *GetInviteRequest, opts ...grpc.CallOption) (*Invite, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Invite)
	err := c.cc.Invoke(ctx, InviteService_GetInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inviteServiceClient) RespondInvite(ctx context.Context, in *RespondInviteRequest, opts ...grpc.CallOption) (*Invite, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Invite)
	err := c.cc.Invoke(ctx, InviteService_RespondInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inviteServiceClient) ListInvites(ctx context.Context, in *ListInvitesRequest, opts ...grpc.CallOption) (*ListInvitesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInvitesResponse)
	err := c.cc.Invoke(ctx, InviteService_ListInvites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InviteServiceServer is the server API for InviteService service.
// All implementations must embed UnimplementedInviteServiceServer
// for forward compatibility.
type InviteServiceServer interface {
	CreateInvite(context.Context, *CreateInviteRequest) (*Invite, error)
	GetInvite(context.Context, *GetInviteRequest) (*Invite, error)
	RespondInvite(context.Context, *RespondInviteRequest) (*Invite, error)
	ListInvites(context.Context, *ListInvitesRequest) (*ListInvitesResponse, error)
	mustEmbedUnimplementedInviteServiceServer()
}

// UnimplementedInviteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInviteServiceServer struct{}

func (UnimplementedInviteServiceServer) CreateInvite(context.Context, *CreateInviteRequest) (*Invite, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInvite not implemented")
}
func (UnimplementedInviteServiceServer) GetInvite(context.Context, *GetInviteRequest) (*Invite, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInvite not implemented")
}
func (UnimplementedInviteServiceServer) RespondInvite(context.Context, *RespondInviteRequest) (*Invite, error) {
	return nil, status.Error(codes.Unimplemented, "method RespondInvite not implemented")
}
func (UnimplementedInviteServiceServer) ListInvites(context.Context, *ListInvitesRequest) (*ListInvitesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInvites not implemented")
}
func (UnimplementedInviteServiceServer) mustEmbedUnimplementedInviteServiceServer() {}
func (UnimplementedInviteServiceServer) testEmbeddedByValue()                       {}

// UnsafeInviteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InviteServiceServer will
// result in compilation errors.
type UnsafeInviteServiceServer interface {
	mustEmbedUnimplementedInviteServiceServer()
}

func RegisterInviteServiceServer(s grpc.ServiceRegistrar, srv InviteServiceServer) {
	// If the following call panics, it indicates UnimplementedInviteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InviteService_ServiceDesc, srv)
}

func _InviteService_CreateInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InviteServiceServer).CreateInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InviteService_CreateInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InviteServiceServer).CreateInvite(ctx, req.(*CreateInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InviteService_GetInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InviteServiceServer).GetInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InviteService_GetInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InviteServiceServer).GetInvite(ctx, req.(*GetInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InviteService_RespondInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RespondInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InviteServiceServer).RespondInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InviteService_RespondInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InviteServiceServer).RespondInvite(ctx, req.(*RespondInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InviteService_ListInvites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInvitesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InviteServiceServer).ListInvites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InviteService_ListInvites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InviteServiceServer).ListInvites(ctx, req.(*ListInvitesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InviteService_ServiceDesc is the grpc.ServiceDesc for InviteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InviteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "social_backend.invite.v1.InviteService",
	HandlerType: (*InviteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateInvite",
			Handler:    _InviteService_CreateInvite_Handler,
		},
		{
			MethodName: "GetInvite",
			Handler:    _InviteService_GetInvite_Handler,
		},
		{
			MethodName: "RespondInvite",
			Handler:    _InviteService_RespondInvite_Handler,
		},
		{
			MethodName: "ListInvites",
			Handler:    _InviteService_ListInvites_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "invite.proto",
}
