// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: invite.proto

package invitev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Invite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	ResourceId    string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	FromPlayerId  string                 `protobuf:"bytes,4,opt,name=from_player_id,json=fromPlayerId,proto3" json:"from_player_id,omitempty"`
	ToPlayerId    string                 `protobuf:"bytes,5,opt,name=to_player_id,json=toPlayerId,proto3" json:"to_player_id,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RespondedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=responded_at,json=respondedAt,proto3" json:"responded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invite) Reset() {
	*x = Invite{}
	mi := &file_invite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invite) ProtoMessage() {}

func (x *Invite) ProtoReflect() protoreflect.Message {
	mi := &file_invite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invite.ProtoReflect.Descriptor instead.
func (*Invite) Descriptor() ([]byte, []int) {
	return file_invite_proto_rawDescGZIP(), []int{0}
}

func (x *Invite) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Invite) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Invite) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *Invite) GetFromPlayerId() string {
	if x != nil {
		return x.FromPlayerId
	}
	return ""
}

func (x *Invite) GetToPlayerId() string {
	if x != nil {
		return x.ToPlayerId
	}
	return ""
}

func (x *Invite) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Invite) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Invite) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Invite) GetRespondedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RespondedAt
	}
	return nil
}

type CreateInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	FromPlayerId  string                 `protobuf:"bytes,3,opt,name=from_player_id,json=fromPlayerId,proto3" json:"from_player_id,omitempty"`
	ToPlayerId    string                 `protobuf:"bytes,4,opt,name=to_player_id,json=toPlayerId,proto3" json:"to_player_id,omitempty"`
	TtlSeconds    int32                  `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInviteRequest) Reset() {
	*x = CreateInviteRequest{}
	mi := &file_invite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteRequest) ProtoMessage() {}

func (x *CreateInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInviteRequest.ProtoReflect.Descriptor instead.
func (*CreateInviteRequest) Descriptor() ([]byte, []int) {
	return file_invite_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInviteRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CreateInviteRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CreateInviteRequest) GetFromPlayerId() string {
	if x != nil {
		return x.FromPlayerId
	}
	return ""
}

func (x *CreateInviteRequest) GetToPlayerId() string {
	if x != nil {
		return x.ToPlayerId
	}
	return ""
}

func (x *CreateInviteRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type GetInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteId      string                 `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInviteRequest) Reset() {
	*x = GetInviteRequest{}
	mi := &file_invite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInviteRequest) ProtoMessage() {}

func (x *GetInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInviteRequest.ProtoReflect.Descriptor instead.
func (*GetInviteRequest) Descriptor() ([]byte, []int) {
	return file_invite_proto_rawDescGZIP(), []int{2}
}

func (x *GetInviteRequest) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

type RespondInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteId      string                 `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
	ActorPlayerId string                 `protobuf:"bytes,2,opt,name=actor_player_id,json=actorPlayerId,proto3" json:"actor_player_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondInviteRequest) Reset() {
	*x = RespondInviteRequest{}
	mi := &file_invite_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondInviteRequest) ProtoMessage() {}

func (x *RespondInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invite_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondInviteRequest.ProtoReflect.Descriptor instead.
func (*RespondInviteRequest) Descriptor() ([]byte, []int) {
	return file_invite_proto_rawDescGZIP(), []int{3}
}

func (x *RespondInviteRequest) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

func (x *RespondInviteRequest) GetActorPlayerId() string {
	if x != nil {
		return x.ActorPlayerId
	}
	return ""
}

func (x *RespondInviteRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type ListInvitesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvitesRequest) Reset() {
	*x = ListInvitesRequest{}
	mi := &file_invite_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvitesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvitesRequest) ProtoMessage() {}

func (x *ListInvitesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invite_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvitesRequest.ProtoReflect.Descriptor instead.
func (*ListInvitesRequest) Descriptor() ([]byte, []int) {
	return file_invite_proto_rawDescGZIP(), []int{4}
}

func (x *ListInvitesRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ListInvitesRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ListInvitesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListInvitesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Invites       []*Invite              `protobuf:"bytes,4,rep,name=invites,proto3" json:"invites,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvitesResponse) Reset() {
	*x = ListInvitesResponse{}
	mi := &file_invite_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvitesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvitesResponse) ProtoMessage() {}

func (x *ListInvitesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invite_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvitesResponse.ProtoReflect.Descriptor instead.
func (*ListInvitesResponse) Descriptor() ([]byte, []int) {
	return file_invite_proto_rawDescGZIP(), []int{5}
}

func (x *ListInvitesResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ListInvitesResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ListInvitesResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListInvitesResponse) GetInvites() []*Invite {
	if x != nil {
		return x.Invites
	}
	return nil
}

var File_invite_proto protoreflect.FileDescriptor

const file_invite_proto_rawDesc = "" +
	"\n" +
	"\finvite.proto\x12\x18social_backend.invite.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe6\x02\n" +
	"\x06Invite\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\x12$\n" +
	"\x0efrom_player_id\x18\x04 \x01(\tR\ffromPlayerId\x12 \n" +
	"\fto_player_id\x18\x05 \x01(\tR\n" +
	"toPlayerId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12=\n" +
	"\fresponded_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vrespondedAt\"\xb7\x01\n" +
	"\x13CreateInviteRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12$\n" +
	"\x0efrom_player_id\x18\x03 \x01(\tR\ffromPlayerId\x12 \n" +
	"\fto_player_id\x18\x04 \x01(\tR\n" +
	"toPlayerId\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\x05R\n" +
	"ttlSeconds\"/\n" +
	"\x10GetInviteRequest\x12\x1b\n" +
	"\tinvite_id\x18\x01 \x01(\tR\binviteId\"s\n" +
	"\x14RespondInviteRequest\x12\x1b\n" +
	"\tinvite_id\x18\x01 \x01(\tR\binviteId\x12&\n" +
	"\x0factor_player_id\x18\x02 \x01(\tR\ractorPlayerId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"]\n" +
	"\x12ListInvitesRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x9a\x01\n" +
	"\x13ListInvitesResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12:\n" +
	"\ainvites\x18\x04 \x03(\v2 .social_backend.invite.v1.InviteR\ainvites2\x9a\x03\n" +
	"\rInviteService\x12_\n" +
	"\fCreateInvite\x12-.social_backend.invite.v1.CreateInviteRequest\x1a .social_backend.invite.v1.Invite\x12Y\n" +
	"\tGetInvite\x12*.social_backend.invite.v1.GetInviteRequest\x1a .social_backend.invite.v1.Invite\x12a\n" +
	"\rRespondInvite\x12..social_backend.invite.v1.RespondInviteRequest\x1a .social_backend.invite.v1.Invite\x12j\n" +
	"\vListInvites\x12,.social_backend.invite.v1.ListInvitesRequest\x1a-.social_backend.invite.v1.ListInvitesResponseB\xea\x01\n" +
	"\x1ccom.social_backend.invite.v1B\vInviteProtoP\x01Z?github.com/xyun1996/social_backend/api/proto/invite/v1;invitev1\xa2\x02\x03SIX\xaa\x02\x17SocialBackend.Invite.V1\xca\x02\x17SocialBackend\\Invite\\V1\xe2\x02#SocialBackend\\Invite\\V1\\GPBMetadata\xea\x02\x19SocialBackend::Invite::V1b\x06proto3"

var (
	file_invite_proto_rawDescOnce sync.Once
	file_invite_proto_rawDescData []byte
)

func file_invite_proto_rawDescGZIP() []byte {
	file_invite_proto_rawDescOnce.Do(func() {
		file_invite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_invite_proto_rawDesc), len(file_invite_proto_rawDesc)))
	})
	return file_invite_proto_rawDescData
}

var file_invite_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_invite_proto_goTypes = []any{
	(*Invite)(nil),                // 0: social_backend.invite.v1.Invite
	(*CreateInviteRequest)(nil),   // 1: social_backend.invite.v1.CreateInviteRequest
	(*GetInviteRequest)(nil),      // 2: social_backend.invite.v1.GetInviteRequest
	(*RespondInviteRequest)(nil),  // 3: social_backend.invite.v1.RespondInviteRequest
	(*ListInvitesRequest)(nil),    // 4: social_backend.invite.v1.ListInvitesRequest
	(*ListInvitesResponse)(nil),   // 5: social_backend.invite.v1.ListInvitesResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_invite_proto_depIdxs = []int32{
	6, // 0: social_backend.invite.v1.Invite.created_at:type_name -> google.protobuf.Timestamp
	6, // 1: social_backend.invite.v1.Invite.expires_at:type_name -> google.protobuf.Timestamp
	6, // 2: social_backend.invite.v1.Invite.responded_at:type_name -> google.protobuf.Timestamp
	0, // 3: social_backend.invite.v1.ListInvitesResponse.invites:type_name -> social_backend.invite.v1.Invite
	1, // 4: social_backend.invite.v1.InviteService.CreateInvite:input_type -> social_backend.invite.v1.CreateInviteRequest
	2, // 5: social_backend.invite.v1.InviteService.GetInvite:input_type -> social_backend.invite.v1.GetInviteRequest
	3, // 6: social_backend.invite.v1.InviteService.RespondInvite:input_type -> social_backend.invite.v1.RespondInviteRequest
	4, // 7: social_backend.invite.v1.InviteService.ListInvites:input_type -> social_backend.invite.v1.ListInvitesRequest
	0, // 8: social_backend.invite.v1.InviteService.CreateInvite:output_type -> social_backend.invite.v1.Invite
	0, // 9: social_backend.invite.v1.InviteService.GetInvite:output_type -> social_backend.invite.v1.Invite
	0, // 10: social_backend.invite.v1.InviteService.RespondInvite:output_type -> social_backend.invite.v1.Invite
	5, // 11: social_backend.invite.v1.InviteService.ListInvites:output_type -> social_backend.invite.v1.ListInvitesResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_invite_proto_init() }
func file_invite_proto_init() {
	if File_invite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_invite_proto_rawDesc), len(file_invite_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_invite_proto_goTypes,
		DependencyIndexes: file_invite_proto_depIdxs,
		MessageInfos:      file_invite_proto_msgTypes,
	}.Build()
	File_invite_proto = out.File
	file_invite_proto_goTypes = nil
	file_invite_proto_depIdxs = nil
}
