// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: social/v1/social.proto

package socialv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromPlayerId  string                 `protobuf:"bytes,2,opt,name=from_player_id,json=fromPlayerId,proto3" json:"from_player_id,omitempty"`
	ToPlayerId    string                 `protobuf:"bytes,3,opt,name=to_player_id,json=toPlayerId,proto3" json:"to_player_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequest) Reset() {
	*x = FriendRequest{}
	mi := &file_social_v1_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequest) ProtoMessage() {}

func (x *FriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequest.ProtoReflect.Descriptor instead.
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{0}
}

func (x *FriendRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FriendRequest) GetFromPlayerId() string {
	if x != nil {
		return x.FromPlayerId
	}
	return ""
}

func (x *FriendRequest) GetToPlayerId() string {
	if x != nil {
		return x.ToPlayerId
	}
	return ""
}

func (x *FriendRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FriendRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type BlockRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	BlockedId     string                 `protobuf:"bytes,2,opt,name=blocked_id,json=blockedId,proto3" json:"blocked_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRecord) Reset() {
	*x = BlockRecord{}
	mi := &file_social_v1_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRecord) ProtoMessage() {}

func (x *BlockRecord) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRecord.ProtoReflect.Descriptor instead.
func (*BlockRecord) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{1}
}

func (x *BlockRecord) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *BlockRecord) GetBlockedId() string {
	if x != nil {
		return x.BlockedId
	}
	return ""
}

func (x *BlockRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type SendFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromPlayerId  string                 `protobuf:"bytes,1,opt,name=from_player_id,json=fromPlayerId,proto3" json:"from_player_id,omitempty"`
	ToPlayerId    string                 `protobuf:"bytes,2,opt,name=to_player_id,json=toPlayerId,proto3" json:"to_player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestRequest) Reset() {
	*x = SendFriendRequestRequest{}
	mi := &file_social_v1_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestRequest) ProtoMessage() {}

func (x *SendFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*SendFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{2}
}

func (x *SendFriendRequestRequest) GetFromPlayerId() string {
	if x != nil {
		return x.FromPlayerId
	}
	return ""
}

func (x *SendFriendRequestRequest) GetToPlayerId() string {
	if x != nil {
		return x.ToPlayerId
	}
	return ""
}

type AcceptFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ActorPlayerId string                 `protobuf:"bytes,2,opt,name=actor_player_id,json=actorPlayerId,proto3" json:"actor_player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendRequestRequest) Reset() {
	*x = AcceptFriendRequestRequest{}
	mi := &file_social_v1_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendRequestRequest) ProtoMessage() {}

func (x *AcceptFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*AcceptFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptFriendRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AcceptFriendRequestRequest) GetActorPlayerId() string {
	if x != nil {
		return x.ActorPlayerId
	}
	return ""
}

type ListFriendRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendRequestsRequest) Reset() {
	*x = ListFriendRequestsRequest{}
	mi := &file_social_v1_social_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendRequestsRequest) ProtoMessage() {}

func (x *ListFriendRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListFriendRequestsRequest) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{4}
}

func (x *ListFriendRequestsRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ListFriendRequestsRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ListFriendRequestsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListFriendRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Requests      []*FriendRequest       `protobuf:"bytes,4,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendRequestsResponse) Reset() {
	*x = ListFriendRequestsResponse{}
	mi := &file_social_v1_social_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendRequestsResponse) ProtoMessage() {}

func (x *ListFriendRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListFriendRequestsResponse) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{5}
}

func (x *ListFriendRequestsResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ListFriendRequestsResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ListFriendRequestsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListFriendRequestsResponse) GetRequests() []*FriendRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type ListFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsRequest) Reset() {
	*x = ListFriendsRequest{}
	mi := &file_social_v1_social_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsRequest) ProtoMessage() {}

func (x *ListFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsRequest.ProtoReflect.Descriptor instead.
func (*ListFriendsRequest) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{6}
}

func (x *ListFriendsRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type ListFriendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Friends       []string               `protobuf:"bytes,2,rep,name=friends,proto3" json:"friends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsResponse) Reset() {
	*x = ListFriendsResponse{}
	mi := &file_social_v1_social_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsResponse) ProtoMessage() {}

func (x *ListFriendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsResponse.ProtoReflect.Descriptor instead.
func (*ListFriendsResponse) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{7}
}

func (x *ListFriendsResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ListFriendsResponse) GetFriends() []string {
	if x != nil {
		return x.Friends
	}
	return nil
}

type BlockPlayerRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlayerId        string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	BlockedPlayerId string                 `protobuf:"bytes,2,opt,name=blocked_player_id,json=blockedPlayerId,proto3" json:"blocked_player_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BlockPlayerRequest) Reset() {
	*x = BlockPlayerRequest{}
	mi := &file_social_v1_social_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockPlayerRequest) ProtoMessage() {}

func (x *BlockPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockPlayerRequest.ProtoReflect.Descriptor instead.
func (*BlockPlayerRequest) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{8}
}

func (x *BlockPlayerRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *BlockPlayerRequest) GetBlockedPlayerId() string {
	if x != nil {
		return x.BlockedPlayerId
	}
	return ""
}

type ListBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlocksRequest) Reset() {
	*x = ListBlocksRequest{}
	mi := &file_social_v1_social_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlocksRequest) ProtoMessage() {}

func (x *ListBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlocksRequest.ProtoReflect.Descriptor instead.
func (*ListBlocksRequest) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{9}
}

func (x *ListBlocksRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type ListBlocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Blocks        []string               `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlocksResponse) Reset() {
	*x = ListBlocksResponse{}
	mi := &file_social_v1_social_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlocksResponse) ProtoMessage() {}

func (x *ListBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlocksResponse.ProtoReflect.Descriptor instead.
func (*ListBlocksResponse) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{10}
}

func (x *ListBlocksResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ListBlocksResponse) GetBlocks() []string {
	if x != nil {
		return x.Blocks
	}
	return nil
}

var File_social_v1_social_proto protoreflect.FileDescriptor

const file_social_v1_social_proto_rawDesc = "" +
	"\n" +
	"\x16social/v1/social.proto\x12\x18social_backend.social.v1\"\x9e\x01\n" +
	"\rFriendRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x0efrom_player_id\x18\x02 \x01(\tR\ffromPlayerId\x12 \n" +
	"\fto_player_id\x18\x03 \x01(\tR\n" +
	"toPlayerId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"h\n" +
	"\vBlockRecord\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"blocked_id\x18\x02 \x01(\tR\tblockedId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"b\n" +
	"\x18SendFriendRequestRequest\x12$\n" +
	"\x0efrom_player_id\x18\x01 \x01(\tR\ffromPlayerId\x12 \n" +
	"\fto_player_id\x18\x02 \x01(\tR\n" +
	"toPlayerId\"c\n" +
	"\x1aAcceptFriendRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12&\n" +
	"\x0factor_player_id\x18\x02 \x01(\tR\ractorPlayerId\"d\n" +
	"\x19ListFriendRequestsRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xaa\x01\n" +
	"\x1aListFriendRequestsResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12C\n" +
	"\brequests\x18\x04 \x03(\v2'.social_backend.social.v1.FriendRequestR\brequests\"1\n" +
	"\x12ListFriendsRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"L\n" +
	"\x13ListFriendsResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x18\n" +
	"\afriends\x18\x02 \x03(\tR\afriends\"]\n" +
	"\x12BlockPlayerRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12*\n" +
	"\x11blocked_player_id\x18\x02 \x01(\tR\x0fblockedPlayerId\"0\n" +
	"\x11ListBlocksRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"I\n" +
	"\x12ListBlocksResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x16\n" +
	"\x06blocks\x18\x02 \x03(\tR\x06blocks2\xb1\x05\n" +
	"\rSocialService\x12p\n" +
	"\x11SendFriendRequest\x122.social_backend.social.v1.SendFriendRequestRequest\x1a'.social_backend.social.v1.FriendRequest\x12t\n" +
	"\x13AcceptFriendRequest\x124.social_backend.social.v1.AcceptFriendRequestRequest\x1a'.social_backend.social.v1.FriendRequest\x12\x7f\n" +
	"\x12ListFriendRequests\x123.social_backend.social.v1.ListFriendRequestsRequest\x1a4.social_backend.social.v1.ListFriendRequestsResponse\x12j\n" +
	"\vListFriends\x12,.social_backend.social.v1.ListFriendsRequest\x1a-.social_backend.social.v1.ListFriendsResponse\x12b\n" +
	"\vBlockPlayer\x12,.social_backend.social.v1.BlockPlayerRequest\x1a%.social_backend.social.v1.BlockRecord\x12g\n" +
	"\n" +
	"ListBlocks\x12+.social_backend.social.v1.ListBlocksRequest\x1a,.social_backend.social.v1.ListBlocksResponseB\xea\x01\n" +
	"\x1ccom.social_backend.social.v1B\vSocialProtoP\x01Z?github.com/xyun1996/social_backend/api/proto/social/v1;socialv1\xa2\x02\x03SSX\xaa\x02\x17SocialBackend.Social.V1\xca\x02\x17SocialBackend\\Social\\V1\xe2\x02#SocialBackend\\Social\\V1\\GPBMetadata\xea\x02\x19SocialBackend::Social::V1b\x06proto3"

var (
	file_social_v1_social_proto_rawDescOnce sync.Once
	file_social_v1_social_proto_rawDescData []byte
)

func file_social_v1_social_proto_rawDescGZIP() []byte {
	file_social_v1_social_proto_rawDescOnce.Do(func() {
		file_social_v1_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_social_v1_social_proto_rawDesc), len(file_social_v1_social_proto_rawDesc)))
	})
	return file_social_v1_social_proto_rawDescData
}

var file_social_v1_social_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_social_v1_social_proto_goTypes = []any{
	(*FriendRequest)(nil),              // 0: social_backend.social.v1.FriendRequest
	(*BlockRecord)(nil),                // 1: social_backend.social.v1.BlockRecord
	(*SendFriendRequestRequest)(nil),   // 2: social_backend.social.v1.SendFriendRequestRequest
	(*AcceptFriendRequestRequest)(nil), // 3: social_backend.social.v1.AcceptFriendRequestRequest
	(*ListFriendRequestsRequest)(nil),  // 4: social_backend.social.v1.ListFriendRequestsRequest
	(*ListFriendRequestsResponse)(nil), // 5: social_backend.social.v1.ListFriendRequestsResponse
	(*ListFriendsRequest)(nil),         // 6: social_backend.social.v1.ListFriendsRequest
	(*ListFriendsResponse)(nil),        // 7: social_backend.social.v1.ListFriendsResponse
	(*BlockPlayerRequest)(nil),         // 8: social_backend.social.v1.BlockPlayerRequest
	(*ListBlocksRequest)(nil),          // 9: social_backend.social.v1.ListBlocksRequest
	(*ListBlocksResponse)(nil),         // 10: social_backend.social.v1.ListBlocksResponse
}
var file_social_v1_social_proto_depIdxs = []int32{
	0,  // 0: social_backend.social.v1.ListFriendRequestsResponse.requests:type_name -> social_backend.social.v1.FriendRequest
	2,  // 1: social_backend.social.v1.SocialService.SendFriendRequest:input_type -> social_backend.social.v1.SendFriendRequestRequest
	3,  // 2: social_backend.social.v1.SocialService.AcceptFriendRequest:input_type -> social_backend.social.v1.AcceptFriendRequestRequest
	4,  // 3: social_backend.social.v1.SocialService.ListFriendRequests:input_type -> social_backend.social.v1.ListFriendRequestsRequest
	6,  // 4: social_backend.social.v1.SocialService.ListFriends:input_type -> social_backend.social.v1.ListFriendsRequest
	8,  // 5: social_backend.social.v1.SocialService.BlockPlayer:input_type -> social_backend.social.v1.BlockPlayerRequest
	9,  // 6: social_backend.social.v1.SocialService.ListBlocks:input_type -> social_backend.social.v1.ListBlocksRequest
	0,  // 7: social_backend.social.v1.SocialService.SendFriendRequest:output_type -> social_backend.social.v1.FriendRequest
	0,  // 8: social_backend.social.v1.SocialService.AcceptFriendRequest:output_type -> social_backend.social.v1.FriendRequest
	5,  // 9: social_backend.social.v1.SocialService.ListFriendRequests:output_type -> social_backend.social.v1.ListFriendRequestsResponse
	7,  // 10: social_backend.social.v1.SocialService.ListFriends:output_type -> social_backend.social.v1.ListFriendsResponse
	1,  // 11: social_backend.social.v1.SocialService.BlockPlayer:output_type -> social_backend.social.v1.BlockRecord
	10, // 12: social_backend.social.v1.SocialService.ListBlocks:output_type -> social_backend.social.v1.ListBlocksResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_social_v1_social_proto_init() }
func file_social_v1_social_proto_init() {
	if File_social_v1_social_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_social_v1_social_proto_rawDesc), len(file_social_v1_social_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_social_v1_social_proto_goTypes,
		DependencyIndexes: file_social_v1_social_proto_depIdxs,
		MessageInfos:      file_social_v1_social_proto_msgTypes,
	}.Build()
	File_social_v1_social_proto = out.File
	file_social_v1_social_proto_goTypes = nil
	file_social_v1_social_proto_depIdxs = nil
}
