// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: guild/v1/guild.proto

package guildv1

import (
	context "context"
	v1 "github.com/xyun1996/social_backend/api/proto/invite/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GuildService_CreateGuild_FullMethodName             = "/social_backend.guild.v1.GuildService/CreateGuild"
	GuildService_GetGuild_FullMethodName                = "/social_backend.guild.v1.GuildService/GetGuild"
	GuildService_CreateGuildInvite_FullMethodName       = "/social_backend.guild.v1.GuildService/CreateGuildInvite"
	GuildService_JoinGuild_FullMethodName               = "/social_backend.guild.v1.GuildService/JoinGuild"
	GuildService_UpdateGuildAnnouncement_FullMethodName = "/social_backend.guild.v1.GuildService/UpdateGuildAnnouncement"
	GuildService_ListMemberStates_FullMethodName        = "/social_backend.guild.v1.GuildService/ListMemberStates"
	GuildService_ListGuildLogs_FullMethodName           = "/social_backend.guild.v1.GuildService/ListGuildLogs"
)

// GuildServiceClient is the client API for GuildService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GuildServiceClient interface {
	CreateGuild(ctx context.Context, in *CreateGuildRequest, opts ...grpc.CallOption) (*Guild, error)
	GetGuild(ctx context.Context, in *GetGuildRequest, opts ...grpc.CallOption) (*Guild, error)
	CreateGuildInvite(ctx context.Context, in *CreateGuildInviteRequest, opts ...grpc.CallOption) (*v1.Invite, error)
	JoinGuild(ctx context.Context, in *JoinGuildRequest, opts ...grpc.CallOption) (*Guild, error)
	UpdateGuildAnnouncement(ctx context.Context, in *UpdateGuildAnnouncementRequest, opts ...grpc.CallOption) (*Guild, error)
	ListMemberStates(ctx context.Context, in *GetGuildRequest, opts ...grpc.CallOption) (*ListMemberStatesResponse, error)
	ListGuildLogs(ctx context.Context, in *GetGuildRequest, opts ...grpc.CallOption) (*ListGuildLogsResponse, error)
}

type guildServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGuildServiceClient(cc grpc.ClientConnInterface) GuildServiceClient {
	return &guildServiceClient{cc}
}

func (c *guildServiceClient) CreateGuild(ctx context.Context, in *CreateGuildRequest, opts ...grpc.CallOption) (*Guild, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Guild)
	err := c.cc.Invoke(ctx, GuildService_CreateGuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildServiceClient) GetGuild(ctx context.Context, in *GetGuildRequest, opts ...grpc.CallOption) (*Guild, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Guild)
	err := c.cc.Invoke(ctx, GuildService_GetGuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildServiceClient) CreateGuildInvite(ctx context.Context, in *CreateGuildInviteRequest, opts ...grpc.CallOption) (*v1.Invite, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Invite)
	err := c.cc.Invoke(ctx, GuildService_CreateGuildInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildServiceClient) JoinGuild(ctx context.Context, in *JoinGuildRequest, opts ...grpc.CallOption) (*Guild, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Guild)
	err := c.cc.Invoke(ctx, GuildService_JoinGuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildServiceClient) UpdateGuildAnnouncement(ctx context.Context, in *UpdateGuildAnnouncementRequest, opts ...grpc.CallOption) (*Guild, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Guild)
	err := c.cc.Invoke(ctx, GuildService_UpdateGuildAnnouncement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildServiceClient) ListMemberStates(ctx context.Context, in *GetGuildRequest, opts ...grpc.CallOption) (*ListMemberStatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMemberStatesResponse)
	err := c.cc.Invoke(ctx, GuildService_ListMemberStates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildServiceClient) ListGuildLogs(ctx context.Context, in *GetGuildRequest, opts ...grpc.CallOption) (*ListGuildLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGuildLogsResponse)
	err := c.cc.Invoke(ctx, GuildService_ListGuildLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuildServiceServer is the server API for GuildService service.
// All implementations must embed UnimplementedGuildServiceServer
// for forward compatibility.
type GuildServiceServer interface {
	CreateGuild(context.Context, *CreateGuildRequest) (*Guild, error)
	GetGuild(context.Context, *GetGuildRequest) (*Guild, error)
	CreateGuildInvite(context.Context, *CreateGuildInviteRequest) (*v1.Invite, error)
	JoinGuild(context.Context, *JoinGuildRequest) (*Guild, error)
	UpdateGuildAnnouncement(context.Context, *UpdateGuildAnnouncementRequest) (*Guild, error)
	ListMemberStates(context.Context, *GetGuildRequest) (*ListMemberStatesResponse, error)
	ListGuildLogs(context.Context, *GetGuildRequest) (*ListGuildLogsResponse, error)
	mustEmbedUnimplementedGuildServiceServer()
}

// UnimplementedGuildServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGuildServiceServer struct{}

func (UnimplementedGuildServiceServer) CreateGuild(context.Context, *CreateGuildRequest) (*Guild, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGuild not implemented")
}
func (UnimplementedGuildServiceServer) GetGuild(context.Context, *GetGuildRequest) (*Guild, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGuild not implemented")
}
func (UnimplementedGuildServiceServer) CreateGuildInvite(context.Context, *CreateGuildInviteRequest) (*v1.Invite, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGuildInvite not implemented")
}
func (UnimplementedGuildServiceServer) JoinGuild(context.Context, *JoinGuildRequest) (*Guild, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinGuild not implemented")
}
func (UnimplementedGuildServiceServer) UpdateGuildAnnouncement(context.Context, *UpdateGuildAnnouncementRequest) (*Guild, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGuildAnnouncement not implemented")
}
func (UnimplementedGuildServiceServer) ListMemberStates(context.Context, *GetGuildRequest) (*ListMemberStatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMemberStates not implemented")
}
func (UnimplementedGuildServiceServer) ListGuildLogs(context.Context, *GetGuildRequest) (*ListGuildLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGuildLogs not implemented")
}
func (UnimplementedGuildServiceServer) mustEmbedUnimplementedGuildServiceServer() {}
func (UnimplementedGuildServiceServer) testEmbeddedByValue()                      {}

// UnsafeGuildServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuildServiceServer will
// result in compilation errors.
type UnsafeGuildServiceServer interface {
	mustEmbedUnimplementedGuildServiceServer()
}

func RegisterGuildServiceServer(s grpc.ServiceRegistrar, srv GuildServiceServer) {
	// If the following call panics, it indicates UnimplementedGuildServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GuildService_ServiceDesc, srv)
}

func _GuildService_CreateGuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServiceServer).CreateGuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildService_CreateGuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServiceServer).CreateGuild(ctx, req.(*CreateGuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuildService_GetGuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServiceServer).GetGuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildService_GetGuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServiceServer).GetGuild(ctx, req.(*GetGuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuildService_CreateGuildInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGuildInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServiceServer).CreateGuildInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildService_CreateGuildInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServiceServer).CreateGuildInvite(ctx, req.(*CreateGuildInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuildService_JoinGuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinGuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServiceServer).JoinGuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildService_JoinGuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServiceServer).JoinGuild(ctx, req.(*JoinGuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuildService_UpdateGuildAnnouncement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGuildAnnouncementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServiceServer).UpdateGuildAnnouncement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildService_UpdateGuildAnnouncement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServiceServer).UpdateGuildAnnouncement(ctx, req.(*UpdateGuildAnnouncementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuildService_ListMemberStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServiceServer).ListMemberStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildService_ListMemberStates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServiceServer).ListMemberStates(ctx, req.(*GetGuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuildService_ListGuildLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServiceServer).ListGuildLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildService_ListGuildLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServiceServer).ListGuildLogs(ctx, req.(*GetGuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GuildService_ServiceDesc is the grpc.ServiceDesc for GuildService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GuildService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "social_backend.guild.v1.GuildService",
	HandlerType: (*GuildServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGuild",
			Handler:    _GuildService_CreateGuild_Handler,
		},
		{
			MethodName: "GetGuild",
			Handler:    _GuildService_GetGuild_Handler,
		},
		{
			MethodName: "CreateGuildInvite",
			Handler:    _GuildService_CreateGuildInvite_Handler,
		},
		{
			MethodName: "JoinGuild",
			Handler:    _GuildService_JoinGuild_Handler,
		},
		{
			MethodName: "UpdateGuildAnnouncement",
			Handler:    _GuildService_UpdateGuildAnnouncement_Handler,
		},
		{
			MethodName: "ListMemberStates",
			Handler:    _GuildService_ListMemberStates_Handler,
		},
		{
			MethodName: "ListGuildLogs",
			Handler:    _GuildService_ListGuildLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guild/v1/guild.proto",
}
