// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ops.proto

package opsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PresenceRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlayerId        string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	SessionId       string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RealmId         string                 `protobuf:"bytes,4,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	Location        string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	LastHeartbeatAt string                 `protobuf:"bytes,6,opt,name=last_heartbeat_at,json=lastHeartbeatAt,proto3" json:"last_heartbeat_at,omitempty"`
	LastSeenAt      string                 `protobuf:"bytes,7,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	ConnectedAt     string                 `protobuf:"bytes,8,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	DisconnectedAt  string                 `protobuf:"bytes,9,opt,name=disconnected_at,json=disconnectedAt,proto3" json:"disconnected_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PresenceRecord) Reset() {
	*x = PresenceRecord{}
	mi := &file_ops_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceRecord) ProtoMessage() {}

func (x *PresenceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceRecord.ProtoReflect.Descriptor instead.
func (*PresenceRecord) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{0}
}

func (x *PresenceRecord) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PresenceRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PresenceRecord) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PresenceRecord) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *PresenceRecord) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *PresenceRecord) GetLastHeartbeatAt() string {
	if x != nil {
		return x.LastHeartbeatAt
	}
	return ""
}

func (x *PresenceRecord) GetLastSeenAt() string {
	if x != nil {
		return x.LastSeenAt
	}
	return ""
}

func (x *PresenceRecord) GetConnectedAt() string {
	if x != nil {
		return x.ConnectedAt
	}
	return ""
}

func (x *PresenceRecord) GetDisconnectedAt() string {
	if x != nil {
		return x.DisconnectedAt
	}
	return ""
}

type SocialSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Friends       []string               `protobuf:"bytes,2,rep,name=friends,proto3" json:"friends,omitempty"`
	Blocks        []string               `protobuf:"bytes,3,rep,name=blocks,proto3" json:"blocks,omitempty"`
	PendingInbox  []string               `protobuf:"bytes,4,rep,name=pending_inbox,json=pendingInbox,proto3" json:"pending_inbox,omitempty"`
	PendingOutbox []string               `protobuf:"bytes,5,rep,name=pending_outbox,json=pendingOutbox,proto3" json:"pending_outbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocialSnapshot) Reset() {
	*x = SocialSnapshot{}
	mi := &file_ops_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocialSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialSnapshot) ProtoMessage() {}

func (x *SocialSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialSnapshot.ProtoReflect.Descriptor instead.
func (*SocialSnapshot) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{1}
}

func (x *SocialSnapshot) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *SocialSnapshot) GetFriends() []string {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *SocialSnapshot) GetBlocks() []string {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *SocialSnapshot) GetPendingInbox() []string {
	if x != nil {
		return x.PendingInbox
	}
	return nil
}

func (x *SocialSnapshot) GetPendingOutbox() []string {
	if x != nil {
		return x.PendingOutbox
	}
	return nil
}

type PlayerOverview struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PlayerId           string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Presence           *PresenceRecord        `protobuf:"bytes,2,opt,name=presence,proto3" json:"presence,omitempty"`
	Friends            []string               `protobuf:"bytes,3,rep,name=friends,proto3" json:"friends,omitempty"`
	Blocks             []string               `protobuf:"bytes,4,rep,name=blocks,proto3" json:"blocks,omitempty"`
	PendingInbox       []string               `protobuf:"bytes,5,rep,name=pending_inbox,json=pendingInbox,proto3" json:"pending_inbox,omitempty"`
	PendingOutbox      []string               `protobuf:"bytes,6,rep,name=pending_outbox,json=pendingOutbox,proto3" json:"pending_outbox,omitempty"`
	FriendCount        int32                  `protobuf:"varint,7,opt,name=friend_count,json=friendCount,proto3" json:"friend_count,omitempty"`
	BlockCount         int32                  `protobuf:"varint,8,opt,name=block_count,json=blockCount,proto3" json:"block_count,omitempty"`
	PendingInboxCount  int32                  `protobuf:"varint,9,opt,name=pending_inbox_count,json=pendingInboxCount,proto3" json:"pending_inbox_count,omitempty"`
	PendingOutboxCount int32                  `protobuf:"varint,10,opt,name=pending_outbox_count,json=pendingOutboxCount,proto3" json:"pending_outbox_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PlayerOverview) Reset() {
	*x = PlayerOverview{}
	mi := &file_ops_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerOverview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerOverview) ProtoMessage() {}

func (x *PlayerOverview) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerOverview.ProtoReflect.Descriptor instead.
func (*PlayerOverview) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerOverview) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerOverview) GetPresence() *PresenceRecord {
	if x != nil {
		return x.Presence
	}
	return nil
}

func (x *PlayerOverview) GetFriends() []string {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *PlayerOverview) GetBlocks() []string {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *PlayerOverview) GetPendingInbox() []string {
	if x != nil {
		return x.PendingInbox
	}
	return nil
}

func (x *PlayerOverview) GetPendingOutbox() []string {
	if x != nil {
		return x.PendingOutbox
	}
	return nil
}

func (x *PlayerOverview) GetFriendCount() int32 {
	if x != nil {
		return x.FriendCount
	}
	return 0
}

func (x *PlayerOverview) GetBlockCount() int32 {
	if x != nil {
		return x.BlockCount
	}
	return 0
}

func (x *PlayerOverview) GetPendingInboxCount() int32 {
	if x != nil {
		return x.PendingInboxCount
	}
	return 0
}

func (x *PlayerOverview) GetPendingOutboxCount() int32 {
	if x != nil {
		return x.PendingOutboxCount
	}
	return 0
}

type PartyMemberState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	IsLeader      bool                   `protobuf:"varint,2,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	IsReady       bool                   `protobuf:"varint,3,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	Presence      string                 `protobuf:"bytes,4,opt,name=presence,proto3" json:"presence,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RealmId       string                 `protobuf:"bytes,6,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyMemberState) Reset() {
	*x = PartyMemberState{}
	mi := &file_ops_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyMemberState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyMemberState) ProtoMessage() {}

func (x *PartyMemberState) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyMemberState.ProtoReflect.Descriptor instead.
func (*PartyMemberState) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{3}
}

func (x *PartyMemberState) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PartyMemberState) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *PartyMemberState) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

func (x *PartyMemberState) GetPresence() string {
	if x != nil {
		return x.Presence
	}
	return ""
}

func (x *PartyMemberState) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PartyMemberState) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *PartyMemberState) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type GuildMemberState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Presence      string                 `protobuf:"bytes,3,opt,name=presence,proto3" json:"presence,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RealmId       string                 `protobuf:"bytes,5,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildMemberState) Reset() {
	*x = GuildMemberState{}
	mi := &file_ops_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildMemberState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildMemberState) ProtoMessage() {}

func (x *GuildMemberState) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildMemberState.ProtoReflect.Descriptor instead.
func (*GuildMemberState) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{4}
}

func (x *GuildMemberState) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GuildMemberState) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GuildMemberState) GetPresence() string {
	if x != nil {
		return x.Presence
	}
	return ""
}

func (x *GuildMemberState) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GuildMemberState) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *GuildMemberState) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type PartySnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Members       []*PartyMemberState    `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartySnapshot) Reset() {
	*x = PartySnapshot{}
	mi := &file_ops_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartySnapshot) ProtoMessage() {}

func (x *PartySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartySnapshot.ProtoReflect.Descriptor instead.
func (*PartySnapshot) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{5}
}

func (x *PartySnapshot) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *PartySnapshot) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PartySnapshot) GetMembers() []*PartyMemberState {
	if x != nil {
		return x.Members
	}
	return nil
}

type GuildSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Members       []*GuildMemberState    `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildSnapshot) Reset() {
	*x = GuildSnapshot{}
	mi := &file_ops_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildSnapshot) ProtoMessage() {}

func (x *GuildSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildSnapshot.ProtoReflect.Descriptor instead.
func (*GuildSnapshot) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{6}
}

func (x *GuildSnapshot) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *GuildSnapshot) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GuildSnapshot) GetMembers() []*GuildMemberState {
	if x != nil {
		return x.Members
	}
	return nil
}

type WorkerJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Attempts      int32                  `protobuf:"varint,5,opt,name=attempts,proto3" json:"attempts,omitempty"`
	LastError     string                 `protobuf:"bytes,6,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	ClaimedBy     string                 `protobuf:"bytes,7,opt,name=claimed_by,json=claimedBy,proto3" json:"claimed_by,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ClaimedAt     string                 `protobuf:"bytes,9,opt,name=claimed_at,json=claimedAt,proto3" json:"claimed_at,omitempty"`
	CompletedAt   string                 `protobuf:"bytes,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerJob) Reset() {
	*x = WorkerJob{}
	mi := &file_ops_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerJob) ProtoMessage() {}

func (x *WorkerJob) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerJob.ProtoReflect.Descriptor instead.
func (*WorkerJob) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{7}
}

func (x *WorkerJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkerJob) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WorkerJob) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *WorkerJob) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkerJob) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *WorkerJob) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *WorkerJob) GetClaimedBy() string {
	if x != nil {
		return x.ClaimedBy
	}
	return ""
}

func (x *WorkerJob) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *WorkerJob) GetClaimedAt() string {
	if x != nil {
		return x.ClaimedAt
	}
	return ""
}

func (x *WorkerJob) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

type WorkerSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Jobs          []*WorkerJob           `protobuf:"bytes,4,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerSnapshot) Reset() {
	*x = WorkerSnapshot{}
	mi := &file_ops_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerSnapshot) ProtoMessage() {}

func (x *WorkerSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerSnapshot.ProtoReflect.Descriptor instead.
func (*WorkerSnapshot) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{8}
}

func (x *WorkerSnapshot) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkerSnapshot) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WorkerSnapshot) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *WorkerSnapshot) GetJobs() []*WorkerJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type MySQLBootstrapService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	MigrationIds  []string               `protobuf:"bytes,3,rep,name=migration_ids,json=migrationIds,proto3" json:"migration_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MySQLBootstrapService) Reset() {
	*x = MySQLBootstrapService{}
	mi := &file_ops_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MySQLBootstrapService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MySQLBootstrapService) ProtoMessage() {}

func (x *MySQLBootstrapService) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MySQLBootstrapService.ProtoReflect.Descriptor instead.
func (*MySQLBootstrapService) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{9}
}

func (x *MySQLBootstrapService) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *MySQLBootstrapService) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *MySQLBootstrapService) GetMigrationIds() []string {
	if x != nil {
		return x.MigrationIds
	}
	return nil
}

type MySQLBootstrapSnapshot struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Count         int32                    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Services      []*MySQLBootstrapService `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MySQLBootstrapSnapshot) Reset() {
	*x = MySQLBootstrapSnapshot{}
	mi := &file_ops_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MySQLBootstrapSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MySQLBootstrapSnapshot) ProtoMessage() {}

func (x *MySQLBootstrapSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MySQLBootstrapSnapshot.ProtoReflect.Descriptor instead.
func (*MySQLBootstrapSnapshot) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{10}
}

func (x *MySQLBootstrapSnapshot) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *MySQLBootstrapSnapshot) GetServices() []*MySQLBootstrapService {
	if x != nil {
		return x.Services
	}
	return nil
}

type RedisWorkerStatusCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedisWorkerStatusCount) Reset() {
	*x = RedisWorkerStatusCount{}
	mi := &file_ops_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisWorkerStatusCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisWorkerStatusCount) ProtoMessage() {}

func (x *RedisWorkerStatusCount) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisWorkerStatusCount.ProtoReflect.Descriptor instead.
func (*RedisWorkerStatusCount) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{11}
}

func (x *RedisWorkerStatusCount) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RedisWorkerStatusCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RedisRuntimeSnapshot struct {
	state                protoimpl.MessageState    `protogen:"open.v1"`
	RedisUrl             string                    `protobuf:"bytes,1,opt,name=redis_url,json=redisUrl,proto3" json:"redis_url,omitempty"`
	PresenceRecordCount  int32                     `protobuf:"varint,2,opt,name=presence_record_count,json=presenceRecordCount,proto3" json:"presence_record_count,omitempty"`
	GatewaySessionCount  int32                     `protobuf:"varint,3,opt,name=gateway_session_count,json=gatewaySessionCount,proto3" json:"gateway_session_count,omitempty"`
	WorkerJobCount       int32                     `protobuf:"varint,4,opt,name=worker_job_count,json=workerJobCount,proto3" json:"worker_job_count,omitempty"`
	WorkerStatusCounters []*RedisWorkerStatusCount `protobuf:"bytes,5,rep,name=worker_status_counters,json=workerStatusCounters,proto3" json:"worker_status_counters,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RedisRuntimeSnapshot) Reset() {
	*x = RedisRuntimeSnapshot{}
	mi := &file_ops_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisRuntimeSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisRuntimeSnapshot) ProtoMessage() {}

func (x *RedisRuntimeSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisRuntimeSnapshot.ProtoReflect.Descriptor instead.
func (*RedisRuntimeSnapshot) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{12}
}

func (x *RedisRuntimeSnapshot) GetRedisUrl() string {
	if x != nil {
		return x.RedisUrl
	}
	return ""
}

func (x *RedisRuntimeSnapshot) GetPresenceRecordCount() int32 {
	if x != nil {
		return x.PresenceRecordCount
	}
	return 0
}

func (x *RedisRuntimeSnapshot) GetGatewaySessionCount() int32 {
	if x != nil {
		return x.GatewaySessionCount
	}
	return 0
}

func (x *RedisRuntimeSnapshot) GetWorkerJobCount() int32 {
	if x != nil {
		return x.WorkerJobCount
	}
	return 0
}

func (x *RedisRuntimeSnapshot) GetWorkerStatusCounters() []*RedisWorkerStatusCount {
	if x != nil {
		return x.WorkerStatusCounters
	}
	return nil
}

type DurableSummary struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Mysql         *MySQLBootstrapSnapshot `protobuf:"bytes,1,opt,name=mysql,proto3" json:"mysql,omitempty"`
	Redis         *RedisRuntimeSnapshot   `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurableSummary) Reset() {
	*x = DurableSummary{}
	mi := &file_ops_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurableSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurableSummary) ProtoMessage() {}

func (x *DurableSummary) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurableSummary.ProtoReflect.Descriptor instead.
func (*DurableSummary) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{13}
}

func (x *DurableSummary) GetMysql() *MySQLBootstrapSnapshot {
	if x != nil {
		return x.Mysql
	}
	return nil
}

func (x *DurableSummary) GetRedis() *RedisRuntimeSnapshot {
	if x != nil {
		return x.Redis
	}
	return nil
}

type GetPlayerPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerPresenceRequest) Reset() {
	*x = GetPlayerPresenceRequest{}
	mi := &file_ops_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerPresenceRequest) ProtoMessage() {}

func (x *GetPlayerPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerPresenceRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerPresenceRequest) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{14}
}

func (x *GetPlayerPresenceRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type GetPartySnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartySnapshotRequest) Reset() {
	*x = GetPartySnapshotRequest{}
	mi := &file_ops_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartySnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartySnapshotRequest) ProtoMessage() {}

func (x *GetPartySnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartySnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetPartySnapshotRequest) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{15}
}

func (x *GetPartySnapshotRequest) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

type GetGuildSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGuildSnapshotRequest) Reset() {
	*x = GetGuildSnapshotRequest{}
	mi := &file_ops_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGuildSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuildSnapshotRequest) ProtoMessage() {}

func (x *GetGuildSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuildSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetGuildSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{16}
}

func (x *GetGuildSnapshotRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

type GetPlayerOverviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerOverviewRequest) Reset() {
	*x = GetPlayerOverviewRequest{}
	mi := &file_ops_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerOverviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerOverviewRequest) ProtoMessage() {}

func (x *GetPlayerOverviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerOverviewRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerOverviewRequest) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{17}
}

func (x *GetPlayerOverviewRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type GetWorkerSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkerSnapshotRequest) Reset() {
	*x = GetWorkerSnapshotRequest{}
	mi := &file_ops_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkerSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkerSnapshotRequest) ProtoMessage() {}

func (x *GetWorkerSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkerSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetWorkerSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{18}
}

func (x *GetWorkerSnapshotRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetWorkerSnapshotRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetMySQLBootstrapSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMySQLBootstrapSnapshotRequest) Reset() {
	*x = GetMySQLBootstrapSnapshotRequest{}
	mi := &file_ops_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMySQLBootstrapSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMySQLBootstrapSnapshotRequest) ProtoMessage() {}

func (x *GetMySQLBootstrapSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMySQLBootstrapSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetMySQLBootstrapSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{19}
}

type GetRedisRuntimeSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRedisRuntimeSnapshotRequest) Reset() {
	*x = GetRedisRuntimeSnapshotRequest{}
	mi := &file_ops_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRedisRuntimeSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRedisRuntimeSnapshotRequest) ProtoMessage() {}

func (x *GetRedisRuntimeSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRedisRuntimeSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetRedisRuntimeSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{20}
}

type GetDurableSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDurableSummaryRequest) Reset() {
	*x = GetDurableSummaryRequest{}
	mi := &file_ops_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDurableSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDurableSummaryRequest) ProtoMessage() {}

func (x *GetDurableSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDurableSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetDurableSummaryRequest) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{21}
}

var File_ops_proto protoreflect.FileDescriptor

const file_ops_proto_rawDesc = "" +
	"\n" +
	"\tops.proto\x12\x15social_backend.ops.v1\"\xb5\x02\n" +
	"\x0ePresenceRecord\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x19\n" +
	"\brealm_id\x18\x04 \x01(\tR\arealmId\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12*\n" +
	"\x11last_heartbeat_at\x18\x06 \x01(\tR\x0flastHeartbeatAt\x12 \n" +
	"\flast_seen_at\x18\a \x01(\tR\n" +
	"lastSeenAt\x12!\n" +
	"\fconnected_at\x18\b \x01(\tR\vconnectedAt\x12'\n" +
	"\x0fdisconnected_at\x18\t \x01(\tR\x0edisconnectedAt\"\xab\x01\n" +
	"\x0eSocialSnapshot\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x18\n" +
	"\afriends\x18\x02 \x03(\tR\afriends\x12\x16\n" +
	"\x06blocks\x18\x03 \x03(\tR\x06blocks\x12#\n" +
	"\rpending_inbox\x18\x04 \x03(\tR\fpendingInbox\x12%\n" +
	"\x0epending_outbox\x18\x05 \x03(\tR\rpendingOutbox\"\x94\x03\n" +
	"\x0ePlayerOverview\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12A\n" +
	"\bpresence\x18\x02 \x01(\v2%.social_backend.ops.v1.PresenceRecordR\bpresence\x12\x18\n" +
	"\afriends\x18\x03 \x03(\tR\afriends\x12\x16\n" +
	"\x06blocks\x18\x04 \x03(\tR\x06blocks\x12#\n" +
	"\rpending_inbox\x18\x05 \x03(\tR\fpendingInbox\x12%\n" +
	"\x0epending_outbox\x18\x06 \x03(\tR\rpendingOutbox\x12!\n" +
	"\ffriend_count\x18\a \x01(\x05R\vfriendCount\x12\x1f\n" +
	"\vblock_count\x18\b \x01(\x05R\n" +
	"blockCount\x12.\n" +
	"\x13pending_inbox_count\x18\t \x01(\x05R\x11pendingInboxCount\x120\n" +
	"\x14pending_outbox_count\x18\n" +
	" \x01(\x05R\x12pendingOutboxCount\"\xd9\x01\n" +
	"\x10PartyMemberState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1b\n" +
	"\tis_leader\x18\x02 \x01(\bR\bisLeader\x12\x19\n" +
	"\bis_ready\x18\x03 \x01(\bR\aisReady\x12\x1a\n" +
	"\bpresence\x18\x04 \x01(\tR\bpresence\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x19\n" +
	"\brealm_id\x18\x06 \x01(\tR\arealmId\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\"\xb5\x01\n" +
	"\x10GuildMemberState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1a\n" +
	"\bpresence\x18\x03 \x01(\tR\bpresence\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x19\n" +
	"\brealm_id\x18\x05 \x01(\tR\arealmId\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\"\x83\x01\n" +
	"\rPartySnapshot\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12A\n" +
	"\amembers\x18\x03 \x03(\v2'.social_backend.ops.v1.PartyMemberStateR\amembers\"\x83\x01\n" +
	"\rGuildSnapshot\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12A\n" +
	"\amembers\x18\x03 \x03(\v2'.social_backend.ops.v1.GuildMemberStateR\amembers\"\x9c\x02\n" +
	"\tWorkerJob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\battempts\x18\x05 \x01(\x05R\battempts\x12\x1d\n" +
	"\n" +
	"last_error\x18\x06 \x01(\tR\tlastError\x12\x1d\n" +
	"\n" +
	"claimed_by\x18\a \x01(\tR\tclaimedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"claimed_at\x18\t \x01(\tR\tclaimedAt\x12!\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\tR\vcompletedAt\"\x88\x01\n" +
	"\x0eWorkerSnapshot\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x124\n" +
	"\x04jobs\x18\x04 \x03(\v2 .social_backend.ops.v1.WorkerJobR\x04jobs\"l\n" +
	"\x15MySQLBootstrapService\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12#\n" +
	"\rmigration_ids\x18\x03 \x03(\tR\fmigrationIds\"x\n" +
	"\x16MySQLBootstrapSnapshot\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12H\n" +
	"\bservices\x18\x02 \x03(\v2,.social_backend.ops.v1.MySQLBootstrapServiceR\bservices\"F\n" +
	"\x16RedisWorkerStatusCount\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xaa\x02\n" +
	"\x14RedisRuntimeSnapshot\x12\x1b\n" +
	"\tredis_url\x18\x01 \x01(\tR\bredisUrl\x122\n" +
	"\x15presence_record_count\x18\x02 \x01(\x05R\x13presenceRecordCount\x122\n" +
	"\x15gateway_session_count\x18\x03 \x01(\x05R\x13gatewaySessionCount\x12(\n" +
	"\x10worker_job_count\x18\x04 \x01(\x05R\x0eworkerJobCount\x12c\n" +
	"\x16worker_status_counters\x18\x05 \x03(\v2-.social_backend.ops.v1.RedisWorkerStatusCountR\x14workerStatusCounters\"\x98\x01\n" +
	"\x0eDurableSummary\x12C\n" +
	"\x05mysql\x18\x01 \x01(\v2-.social_backend.ops.v1.MySQLBootstrapSnapshotR\x05mysql\x12A\n" +
	"\x05redis\x18\x02 \x01(\v2+.social_backend.ops.v1.RedisRuntimeSnapshotR\x05redis\"7\n" +
	"\x18GetPlayerPresenceRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"4\n" +
	"\x17GetPartySnapshotRequest\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\"4\n" +
	"\x17GetGuildSnapshotRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\"7\n" +
	"\x18GetPlayerOverviewRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"F\n" +
	"\x18GetWorkerSnapshotRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\"\n" +
	" GetMySQLBootstrapSnapshotRequest\" \n" +
	"\x1eGetRedisRuntimeSnapshotRequest\"\x1a\n" +
	"\x18GetDurableSummaryRequest2\x99\a\n" +
	"\n" +
	"OpsService\x12k\n" +
	"\x11GetPlayerPresence\x12/.social_backend.ops.v1.GetPlayerPresenceRequest\x1a%.social_backend.ops.v1.PresenceRecord\x12k\n" +
	"\x11GetPlayerOverview\x12/.social_backend.ops.v1.GetPlayerOverviewRequest\x1a%.social_backend.ops.v1.PlayerOverview\x12h\n" +
	"\x10GetPartySnapshot\x12..social_backend.ops.v1.GetPartySnapshotRequest\x1a$.social_backend.ops.v1.PartySnapshot\x12h\n" +
	"\x10GetGuildSnapshot\x12..social_backend.ops.v1.GetGuildSnapshotRequest\x1a$.social_backend.ops.v1.GuildSnapshot\x12k\n" +
	"\x11GetWorkerSnapshot\x12/.social_backend.ops.v1.GetWorkerSnapshotRequest\x1a%.social_backend.ops.v1.WorkerSnapshot\x12\x83\x01\n" +
	"\x19GetMySQLBootstrapSnapshot\x127.social_backend.ops.v1.GetMySQLBootstrapSnapshotRequest\x1a-.social_backend.ops.v1.MySQLBootstrapSnapshot\x12}\n" +
	"\x17GetRedisRuntimeSnapshot\x125.social_backend.ops.v1.GetRedisRuntimeSnapshotRequest\x1a+.social_backend.ops.v1.RedisRuntimeSnapshot\x12k\n" +
	"\x11GetDurableSummary\x12/.social_backend.ops.v1.GetDurableSummaryRequest\x1a%.social_backend.ops.v1.DurableSummaryB\xd2\x01\n" +
	"\x19com.social_backend.ops.v1B\bOpsProtoP\x01Z9github.com/xyun1996/social_backend/api/proto/ops/v1;opsv1\xa2\x02\x03SOX\xaa\x02\x14SocialBackend.Ops.V1\xca\x02\x14SocialBackend\\Ops\\V1\xe2\x02 SocialBackend\\Ops\\V1\\GPBMetadata\xea\x02\x16SocialBackend::Ops::V1b\x06proto3"

var (
	file_ops_proto_rawDescOnce sync.Once
	file_ops_proto_rawDescData []byte
)

func file_ops_proto_rawDescGZIP() []byte {
	file_ops_proto_rawDescOnce.Do(func() {
		file_ops_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ops_proto_rawDesc), len(file_ops_proto_rawDesc)))
	})
	return file_ops_proto_rawDescData
}

var file_ops_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_ops_proto_goTypes = []any{
	(*PresenceRecord)(nil),                   // 0: social_backend.ops.v1.PresenceRecord
	(*SocialSnapshot)(nil),                   // 1: social_backend.ops.v1.SocialSnapshot
	(*PlayerOverview)(nil),                   // 2: social_backend.ops.v1.PlayerOverview
	(*PartyMemberState)(nil),                 // 3: social_backend.ops.v1.PartyMemberState
	(*GuildMemberState)(nil),                 // 4: social_backend.ops.v1.GuildMemberState
	(*PartySnapshot)(nil),                    // 5: social_backend.ops.v1.PartySnapshot
	(*GuildSnapshot)(nil),                    // 6: social_backend.ops.v1.GuildSnapshot
	(*WorkerJob)(nil),                        // 7: social_backend.ops.v1.WorkerJob
	(*WorkerSnapshot)(nil),                   // 8: social_backend.ops.v1.WorkerSnapshot
	(*MySQLBootstrapService)(nil),            // 9: social_backend.ops.v1.MySQLBootstrapService
	(*MySQLBootstrapSnapshot)(nil),           // 10: social_backend.ops.v1.MySQLBootstrapSnapshot
	(*RedisWorkerStatusCount)(nil),           // 11: social_backend.ops.v1.RedisWorkerStatusCount
	(*RedisRuntimeSnapshot)(nil),             // 12: social_backend.ops.v1.RedisRuntimeSnapshot
	(*DurableSummary)(nil),                   // 13: social_backend.ops.v1.DurableSummary
	(*GetPlayerPresenceRequest)(nil),         // 14: social_backend.ops.v1.GetPlayerPresenceRequest
	(*GetPartySnapshotRequest)(nil),          // 15: social_backend.ops.v1.GetPartySnapshotRequest
	(*GetGuildSnapshotRequest)(nil),          // 16: social_backend.ops.v1.GetGuildSnapshotRequest
	(*GetPlayerOverviewRequest)(nil),         // 17: social_backend.ops.v1.GetPlayerOverviewRequest
	(*GetWorkerSnapshotRequest)(nil),         // 18: social_backend.ops.v1.GetWorkerSnapshotRequest
	(*GetMySQLBootstrapSnapshotRequest)(nil), // 19: social_backend.ops.v1.GetMySQLBootstrapSnapshotRequest
	(*GetRedisRuntimeSnapshotRequest)(nil),   // 20: social_backend.ops.v1.GetRedisRuntimeSnapshotRequest
	(*GetDurableSummaryRequest)(nil),         // 21: social_backend.ops.v1.GetDurableSummaryRequest
}
var file_ops_proto_depIdxs = []int32{
	0,  // 0: social_backend.ops.v1.PlayerOverview.presence:type_name -> social_backend.ops.v1.PresenceRecord
	3,  // 1: social_backend.ops.v1.PartySnapshot.members:type_name -> social_backend.ops.v1.PartyMemberState
	4,  // 2: social_backend.ops.v1.GuildSnapshot.members:type_name -> social_backend.ops.v1.GuildMemberState
	7,  // 3: social_backend.ops.v1.WorkerSnapshot.jobs:type_name -> social_backend.ops.v1.WorkerJob
	9,  // 4: social_backend.ops.v1.MySQLBootstrapSnapshot.services:type_name -> social_backend.ops.v1.MySQLBootstrapService
	11, // 5: social_backend.ops.v1.RedisRuntimeSnapshot.worker_status_counters:type_name -> social_backend.ops.v1.RedisWorkerStatusCount
	10, // 6: social_backend.ops.v1.DurableSummary.mysql:type_name -> social_backend.ops.v1.MySQLBootstrapSnapshot
	12, // 7: social_backend.ops.v1.DurableSummary.redis:type_name -> social_backend.ops.v1.RedisRuntimeSnapshot
	14, // 8: social_backend.ops.v1.OpsService.GetPlayerPresence:input_type -> social_backend.ops.v1.GetPlayerPresenceRequest
	17, // 9: social_backend.ops.v1.OpsService.GetPlayerOverview:input_type -> social_backend.ops.v1.GetPlayerOverviewRequest
	15, // 10: social_backend.ops.v1.OpsService.GetPartySnapshot:input_type -> social_backend.ops.v1.GetPartySnapshotRequest
	16, // 11: social_backend.ops.v1.OpsService.GetGuildSnapshot:input_type -> social_backend.ops.v1.GetGuildSnapshotRequest
	18, // 12: social_backend.ops.v1.OpsService.GetWorkerSnapshot:input_type -> social_backend.ops.v1.GetWorkerSnapshotRequest
	19, // 13: social_backend.ops.v1.OpsService.GetMySQLBootstrapSnapshot:input_type -> social_backend.ops.v1.GetMySQLBootstrapSnapshotRequest
	20, // 14: social_backend.ops.v1.OpsService.GetRedisRuntimeSnapshot:input_type -> social_backend.ops.v1.GetRedisRuntimeSnapshotRequest
	21, // 15: social_backend.ops.v1.OpsService.GetDurableSummary:input_type -> social_backend.ops.v1.GetDurableSummaryRequest
	0,  // 16: social_backend.ops.v1.OpsService.GetPlayerPresence:output_type -> social_backend.ops.v1.PresenceRecord
	2,  // 17: social_backend.ops.v1.OpsService.GetPlayerOverview:output_type -> social_backend.ops.v1.PlayerOverview
	5,  // 18: social_backend.ops.v1.OpsService.GetPartySnapshot:output_type -> social_backend.ops.v1.PartySnapshot
	6,  // 19: social_backend.ops.v1.OpsService.GetGuildSnapshot:output_type -> social_backend.ops.v1.GuildSnapshot
	8,  // 20: social_backend.ops.v1.OpsService.GetWorkerSnapshot:output_type -> social_backend.ops.v1.WorkerSnapshot
	10, // 21: social_backend.ops.v1.OpsService.GetMySQLBootstrapSnapshot:output_type -> social_backend.ops.v1.MySQLBootstrapSnapshot
	12, // 22: social_backend.ops.v1.OpsService.GetRedisRuntimeSnapshot:output_type -> social_backend.ops.v1.RedisRuntimeSnapshot
	13, // 23: social_backend.ops.v1.OpsService.GetDurableSummary:output_type -> social_backend.ops.v1.DurableSummary
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_ops_proto_init() }
func file_ops_proto_init() {
	if File_ops_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ops_proto_rawDesc), len(file_ops_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ops_proto_goTypes,
		DependencyIndexes: file_ops_proto_depIdxs,
		MessageInfos:      file_ops_proto_msgTypes,
	}.Build()
	File_ops_proto = out.File
	file_ops_proto_goTypes = nil
	file_ops_proto_depIdxs = nil
}
