// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: ops.proto

package opsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OpsService_GetPlayerPresence_FullMethodName         = "/social_backend.ops.v1.OpsService/GetPlayerPresence"
	OpsService_GetPlayerOverview_FullMethodName         = "/social_backend.ops.v1.OpsService/GetPlayerOverview"
	OpsService_GetPartySnapshot_FullMethodName          = "/social_backend.ops.v1.OpsService/GetPartySnapshot"
	OpsService_GetGuildSnapshot_FullMethodName          = "/social_backend.ops.v1.OpsService/GetGuildSnapshot"
	OpsService_GetWorkerSnapshot_FullMethodName         = "/social_backend.ops.v1.OpsService/GetWorkerSnapshot"
	OpsService_GetMySQLBootstrapSnapshot_FullMethodName = "/social_backend.ops.v1.OpsService/GetMySQLBootstrapSnapshot"
	OpsService_GetRedisRuntimeSnapshot_FullMethodName   = "/social_backend.ops.v1.OpsService/GetRedisRuntimeSnapshot"
	OpsService_GetDurableSummary_FullMethodName         = "/social_backend.ops.v1.OpsService/GetDurableSummary"
)

// OpsServiceClient is the client API for OpsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpsServiceClient interface {
	GetPlayerPresence(ctx context.Context, in *GetPlayerPresenceRequest, opts ...grpc.CallOption) (*PresenceRecord, error)
	GetPlayerOverview(ctx context.Context, in *GetPlayerOverviewRequest, opts ...grpc.CallOption) (*PlayerOverview, error)
	GetPartySnapshot(ctx context.Context, in *GetPartySnapshotRequest, opts ...grpc.CallOption) (*PartySnapshot, error)
	GetGuildSnapshot(ctx context.Context, in *GetGuildSnapshotRequest, opts ...grpc.CallOption) (*GuildSnapshot, error)
	GetWorkerSnapshot(ctx context.Context, in *GetWorkerSnapshotRequest, opts ...grpc.CallOption) (*WorkerSnapshot, error)
	GetMySQLBootstrapSnapshot(ctx context.Context, in *GetMySQLBootstrapSnapshotRequest, opts ...grpc.CallOption) (*MySQLBootstrapSnapshot, error)
	GetRedisRuntimeSnapshot(ctx context.Context, in *GetRedisRuntimeSnapshotRequest, opts ...grpc.CallOption) (*RedisRuntimeSnapshot, error)
	GetDurableSummary(ctx context.Context, in *GetDurableSummaryRequest, opts ...grpc.CallOption) (*DurableSummary, error)
}

type opsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOpsServiceClient(cc grpc.ClientConnInterface) OpsServiceClient {
	return &opsServiceClient{cc}
}

func (c *opsServiceClient) GetPlayerPresence(ctx context.Context, in *GetPlayerPresenceRequest, opts ...grpc.CallOption) (*PresenceRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PresenceRecord)
	err := c.cc.Invoke(ctx, OpsService_GetPlayerPresence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsServiceClient) GetPlayerOverview(ctx context.Context, in *GetPlayerOverviewRequest, opts ...grpc.CallOption) (*PlayerOverview, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerOverview)
	err := c.cc.Invoke(ctx, OpsService_GetPlayerOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsServiceClient) GetPartySnapshot(ctx context.Context, in *GetPartySnapshotRequest, opts ...grpc.CallOption) (*PartySnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartySnapshot)
	err := c.cc.Invoke(ctx, OpsService_GetPartySnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsServiceClient) GetGuildSnapshot(ctx context.Context, in *GetGuildSnapshotRequest, opts ...grpc.CallOption) (*GuildSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuildSnapshot)
	err := c.cc.Invoke(ctx, OpsService_GetGuildSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsServiceClient) GetWorkerSnapshot(ctx context.Context, in *GetWorkerSnapshotRequest, opts ...grpc.CallOption) (*WorkerSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerSnapshot)
	err := c.cc.Invoke(ctx, OpsService_GetWorkerSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsServiceClient) GetMySQLBootstrapSnapshot(ctx context.Context, in *GetMySQLBootstrapSnapshotRequest, opts ...grpc.CallOption) (*MySQLBootstrapSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MySQLBootstrapSnapshot)
	err := c.cc.Invoke(ctx, OpsService_GetMySQLBootstrapSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsServiceClient) GetRedisRuntimeSnapshot(ctx context.Context, in *GetRedisRuntimeSnapshotRequest, opts ...grpc.CallOption) (*RedisRuntimeSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedisRuntimeSnapshot)
	err := c.cc.Invoke(ctx, OpsService_GetRedisRuntimeSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsServiceClient) GetDurableSummary(ctx context.Context, in *GetDurableSummaryRequest, opts ...grpc.CallOption) (*DurableSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DurableSummary)
	err := c.cc.Invoke(ctx, OpsService_GetDurableSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpsServiceServer is the server API for OpsService service.
// All implementations must embed UnimplementedOpsServiceServer
// for forward compatibility.
type OpsServiceServer interface {
	GetPlayerPresence(context.Context, *GetPlayerPresenceRequest) (*PresenceRecord, error)
	GetPlayerOverview(context.Context, *GetPlayerOverviewRequest) (*PlayerOverview, error)
	GetPartySnapshot(context.Context, *GetPartySnapshotRequest) (*PartySnapshot, error)
	GetGuildSnapshot(context.Context, *GetGuildSnapshotRequest) (*GuildSnapshot, error)
	GetWorkerSnapshot(context.Context, *GetWorkerSnapshotRequest) (*WorkerSnapshot, error)
	GetMySQLBootstrapSnapshot(context.Context, *GetMySQLBootstrapSnapshotRequest) (*MySQLBootstrapSnapshot, error)
	GetRedisRuntimeSnapshot(context.Context, *GetRedisRuntimeSnapshotRequest) (*RedisRuntimeSnapshot, error)
	GetDurableSummary(context.Context, *GetDurableSummaryRequest) (*DurableSummary, error)
	mustEmbedUnimplementedOpsServiceServer()
}

// UnimplementedOpsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOpsServiceServer struct{}

func (UnimplementedOpsServiceServer) GetPlayerPresence(context.Context, *GetPlayerPresenceRequest) (*PresenceRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlayerPresence not implemented")
}
func (UnimplementedOpsServiceServer) GetPlayerOverview(context.Context, *GetPlayerOverviewRequest) (*PlayerOverview, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlayerOverview not implemented")
}
func (UnimplementedOpsServiceServer) GetPartySnapshot(context.Context, *GetPartySnapshotRequest) (*PartySnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPartySnapshot not implemented")
}
func (UnimplementedOpsServiceServer) GetGuildSnapshot(context.Context, *GetGuildSnapshotRequest) (*GuildSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGuildSnapshot not implemented")
}
func (UnimplementedOpsServiceServer) GetWorkerSnapshot(context.Context, *GetWorkerSnapshotRequest) (*WorkerSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkerSnapshot not implemented")
}
func (UnimplementedOpsServiceServer) GetMySQLBootstrapSnapshot(context.Context, *GetMySQLBootstrapSnapshotRequest) (*MySQLBootstrapSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMySQLBootstrapSnapshot not implemented")
}
func (UnimplementedOpsServiceServer) GetRedisRuntimeSnapshot(context.Context, *GetRedisRuntimeSnapshotRequest) (*RedisRuntimeSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRedisRuntimeSnapshot not implemented")
}
func (UnimplementedOpsServiceServer) GetDurableSummary(context.Context, *GetDurableSummaryRequest) (*DurableSummary, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDurableSummary not implemented")
}
func (UnimplementedOpsServiceServer) mustEmbedUnimplementedOpsServiceServer() {}
func (UnimplementedOpsServiceServer) testEmbeddedByValue()                    {}

// UnsafeOpsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpsServiceServer will
// result in compilation errors.
type UnsafeOpsServiceServer interface {
	mustEmbedUnimplementedOpsServiceServer()
}

func RegisterOpsServiceServer(s grpc.ServiceRegistrar, srv OpsServiceServer) {
	// If the following call panics, it indicates UnimplementedOpsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OpsService_ServiceDesc, srv)
}

func _OpsService_GetPlayerPresence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerPresenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsServiceServer).GetPlayerPresence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsService_GetPlayerPresence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsServiceServer).GetPlayerPresence(ctx, req.(*GetPlayerPresenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsService_GetPlayerOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerOverviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsServiceServer).GetPlayerOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsService_GetPlayerOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsServiceServer).GetPlayerOverview(ctx, req.(*GetPlayerOverviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsService_GetPartySnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartySnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsServiceServer).GetPartySnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsService_GetPartySnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsServiceServer).GetPartySnapshot(ctx, req.(*GetPartySnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsService_GetGuildSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGuildSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsServiceServer).GetGuildSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsService_GetGuildSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsServiceServer).GetGuildSnapshot(ctx, req.(*GetGuildSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsService_GetWorkerSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkerSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsServiceServer).GetWorkerSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsService_GetWorkerSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsServiceServer).GetWorkerSnapshot(ctx, req.(*GetWorkerSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsService_GetMySQLBootstrapSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMySQLBootstrapSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsServiceServer).GetMySQLBootstrapSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsService_GetMySQLBootstrapSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsServiceServer).GetMySQLBootstrapSnapshot(ctx, req.(*GetMySQLBootstrapSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsService_GetRedisRuntimeSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRedisRuntimeSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsServiceServer).GetRedisRuntimeSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsService_GetRedisRuntimeSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsServiceServer).GetRedisRuntimeSnapshot(ctx, req.(*GetRedisRuntimeSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsService_GetDurableSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDurableSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsServiceServer).GetDurableSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsService_GetDurableSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsServiceServer).GetDurableSummary(ctx, req.(*GetDurableSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OpsService_ServiceDesc is the grpc.ServiceDesc for OpsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "social_backend.ops.v1.OpsService",
	HandlerType: (*OpsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlayerPresence",
			Handler:    _OpsService_GetPlayerPresence_Handler,
		},
		{
			MethodName: "GetPlayerOverview",
			Handler:    _OpsService_GetPlayerOverview_Handler,
		},
		{
			MethodName: "GetPartySnapshot",
			Handler:    _OpsService_GetPartySnapshot_Handler,
		},
		{
			MethodName: "GetGuildSnapshot",
			Handler:    _OpsService_GetGuildSnapshot_Handler,
		},
		{
			MethodName: "GetWorkerSnapshot",
			Handler:    _OpsService_GetWorkerSnapshot_Handler,
		},
		{
			MethodName: "GetMySQLBootstrapSnapshot",
			Handler:    _OpsService_GetMySQLBootstrapSnapshot_Handler,
		},
		{
			MethodName: "GetRedisRuntimeSnapshot",
			Handler:    _OpsService_GetRedisRuntimeSnapshot_Handler,
		},
		{
			MethodName: "GetDurableSummary",
			Handler:    _OpsService_GetDurableSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ops.proto",
}
