// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: party.proto

package partyv1

import (
	v1 "github.com/xyun1996/social_backend/api/proto/invite/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Party struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	MemberIds     []string               `protobuf:"bytes,3,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Party) Reset() {
	*x = Party{}
	mi := &file_party_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Party) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Party) ProtoMessage() {}

func (x *Party) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Party.ProtoReflect.Descriptor instead.
func (*Party) Descriptor() ([]byte, []int) {
	return file_party_proto_rawDescGZIP(), []int{0}
}

func (x *Party) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Party) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *Party) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

func (x *Party) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ReadyState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	IsReady       bool                   `protobuf:"varint,3,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyState) Reset() {
	*x = ReadyState{}
	mi := &file_party_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyState) ProtoMessage() {}

func (x *ReadyState) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyState.ProtoReflect.Descriptor instead.
func (*ReadyState) Descriptor() ([]byte, []int) {
	return file_party_proto_rawDescGZIP(), []int{1}
}

func (x *ReadyState) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *ReadyState) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ReadyState) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

func (x *ReadyState) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type QueueState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	JoinedBy      string                 `protobuf:"bytes,4,opt,name=joined_by,json=joinedBy,proto3" json:"joined_by,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueState) Reset() {
	*x = QueueState{}
	mi := &file_party_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueState) ProtoMessage() {}

func (x *QueueState) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueState.ProtoReflect.Descriptor instead.
func (*QueueState) Descriptor() ([]byte, []int) {
	return file_party_proto_rawDescGZIP(), []int{2}
}

func (x *QueueState) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *QueueState) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *QueueState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QueueState) GetJoinedBy() string {
	if x != nil {
		return x.JoinedBy
	}
	return ""
}

func (x *QueueState) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

type QueueLeaveResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	LeftAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=left_at,json=leftAt,proto3" json:"left_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueLeaveResult) Reset() {
	*x = QueueLeaveResult{}
	mi := &file_party_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueLeaveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueLeaveResult) ProtoMessage() {}

func (x *QueueLeaveResult) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueLeaveResult.ProtoReflect.Descriptor instead.
func (*QueueLeaveResult) Descriptor() ([]byte, []int) {
	return file_party_proto_rawDescGZIP(), []int{3}
}

func (x *QueueLeaveResult) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *QueueLeaveResult) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *QueueLeaveResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QueueLeaveResult) GetLeftAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeftAt
	}
	return nil
}

type QueueHandoff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	PartyId       string                 `protobuf:"bytes,2,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	QueueName     string                 `protobuf:"bytes,3,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	LeaderId      string                 `protobuf:"bytes,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	MemberIds     []string               `protobuf:"bytes,5,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	MemberCount   int32                  `protobuf:"varint,7,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	Members       []*MemberState         `protobuf:"bytes,8,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueHandoff) Reset() {
	*x = QueueHandoff{}
	mi := &file_party_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueHandoff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueHandoff) ProtoMessage() {}

func (x *QueueHandoff) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueHandoff.ProtoReflect.Descriptor instead.
func (*QueueHandoff) Descriptor() ([]byte, []int) {
	return file_party_proto_rawDescGZIP(), []int{4}
}

func (x *QueueHandoff) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *QueueHandoff) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *QueueHandoff) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *QueueHandoff) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *QueueHandoff) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

func (x *QueueHandoff) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *QueueHandoff) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *QueueHandoff) GetMembers() []*MemberState {
	if x != nil {
		return x.Members
	}
	return nil
}

type MemberState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	IsLeader      bool                   `protobuf:"varint,2,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	IsReady       bool                   `protobuf:"varint,3,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	Presence      string                 `protobuf:"bytes,4,opt,name=presence,proto3" json:"presence,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RealmId       string                 `protobuf:"bytes,6,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberState) Reset() {
	*x = MemberState{}
	mi := &file_party_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberState) ProtoMessage() {}

func (x *MemberState) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberState.ProtoReflect.Descriptor instead.
func (*MemberState) Descriptor() ([]byte, []int) {
	return file_party_proto_rawDescGZIP(), []int{5}
}

func (x *MemberState) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *MemberState) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *MemberState) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

func (x *MemberState) GetPresence() string {
	if x != nil {
		return x.Presence
	}
	return ""
}

func (x *MemberState) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MemberState) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *MemberState) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type CreatePartyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderId      string                 `protobuf:"bytes,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePartyRequest) Reset() {
	*x = CreatePartyRequest{}
	mi := &file_party_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePartyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePartyRequest) ProtoMessage() {}

func (x *CreatePartyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePartyRequest.ProtoReflect.Descriptor instead.
func (*CreatePartyRequest) Descriptor() ([]byte, []int) {
	return file_party_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePartyRequest) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

type GetPartyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartyRequest) Reset() {
	*x = GetPartyRequest{}
	mi := &file_party_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartyRequest) ProtoMessage() {}

func (x *GetPartyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartyRequest.ProtoReflect.Descriptor instead.
func (*GetPartyRequest) Descriptor() ([]byte, []int) {
	return file_party_proto_rawDescGZIP(), []int{7}
}

func (x *GetPartyRequest) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

type CreatePartyInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	ActorPlayerId string                 `protobuf:"bytes,2,opt,name=actor_player_id,json=actorPlayerId,proto3" json:"actor_player_id,omitempty"`
	ToPlayerId    string                 `protobuf:"bytes,3,opt,name=to_player_id,json=toPlayerId,proto3" json:"to_player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePartyInviteRequest) Reset() {
	*x = CreatePartyInviteRequest{}
	mi := &file_party_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePartyInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePartyInviteRequest) ProtoMessage() {}

func (x *CreatePartyInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePartyInviteRequest.ProtoReflect.Descriptor instead.
func (*CreatePartyInviteRequest) Descriptor() ([]byte, []int) {
	return file_party_proto_rawDescGZIP(), []int{8}
}

func (x *CreatePartyInviteRequest) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *CreatePartyInviteRequest) GetActorPlayerId() string {
	if x != nil {
		return x.ActorPlayerId
	}
	return ""
}

func (x *CreatePartyInviteRequest) GetToPlayerId() string {
	if x != nil {
		return x.ToPlayerId
	}
	return ""
}

type JoinPartyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	InviteId      string                 `protobuf:"bytes,2,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
	ActorPlayerId string                 `protobuf:"bytes,3,opt,name=actor_player_id,json=actorPlayerId,proto3" json:"actor_player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinPartyRequest) Reset() {
	*x = JoinPartyRequest{}
	mi := &file_party_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinPartyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinPartyRequest) ProtoMessage() {}

func (x *JoinPartyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinPartyRequest.ProtoReflect.Descriptor instead.
func (*JoinPartyRequest) Descriptor() ([]byte, []int) {
	return file_party_proto_rawDescGZIP(), []int{9}
}

func (x *JoinPartyRequest) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *JoinPartyRequest) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

func (x *JoinPartyRequest) GetActorPlayerId() string {
	if x != nil {
		return x.ActorPlayerId
	}
	return ""
}

type SetReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	ActorPlayerId string                 `protobuf:"bytes,2,opt,name=actor_player_id,json=actorPlayerId,proto3" json:"actor_player_id,omitempty"`
	IsReady       bool                   `protobuf:"varint,3,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetReadyRequest) Reset() {
	*x = SetReadyRequest{}
	mi := &file_party_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReadyRequest) ProtoMessage() {}

func (x *SetReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReadyRequest.ProtoReflect.Descriptor instead.
func (*SetReadyRequest) Descriptor() ([]byte, []int) {
	return file_party_proto_rawDescGZIP(), []int{10}
}

func (x *SetReadyRequest) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *SetReadyRequest) GetActorPlayerId() string {
	if x != nil {
		return x.ActorPlayerId
	}
	return ""
}

func (x *SetReadyRequest) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

type JoinQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	ActorPlayerId string                 `protobuf:"bytes,2,opt,name=actor_player_id,json=actorPlayerId,proto3" json:"actor_player_id,omitempty"`
	QueueName     string                 `protobuf:"bytes,3,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinQueueRequest) Reset() {
	*x = JoinQueueRequest{}
	mi := &file_party_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinQueueRequest) ProtoMessage() {}

func (x *JoinQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinQueueRequest.ProtoReflect.Descriptor instead.
func (*JoinQueueRequest) Descriptor() ([]byte, []int) {
	return file_party_proto_rawDescGZIP(), []int{11}
}

func (x *JoinQueueRequest) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *JoinQueueRequest) GetActorPlayerId() string {
	if x != nil {
		return x.ActorPlayerId
	}
	return ""
}

func (x *JoinQueueRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

type LeaveQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	ActorPlayerId string                 `protobuf:"bytes,2,opt,name=actor_player_id,json=actorPlayerId,proto3" json:"actor_player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveQueueRequest) Reset() {
	*x = LeaveQueueRequest{}
	mi := &file_party_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveQueueRequest) ProtoMessage() {}

func (x *LeaveQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveQueueRequest.ProtoReflect.Descriptor instead.
func (*LeaveQueueRequest) Descriptor() ([]byte, []int) {
	return file_party_proto_rawDescGZIP(), []int{12}
}

func (x *LeaveQueueRequest) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *LeaveQueueRequest) GetActorPlayerId() string {
	if x != nil {
		return x.ActorPlayerId
	}
	return ""
}

type ListReadyStatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	ReadyStates   []*ReadyState          `protobuf:"bytes,2,rep,name=ready_states,json=readyStates,proto3" json:"ready_states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReadyStatesResponse) Reset() {
	*x = ListReadyStatesResponse{}
	mi := &file_party_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReadyStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReadyStatesResponse) ProtoMessage() {}

func (x *ListReadyStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReadyStatesResponse.ProtoReflect.Descriptor instead.
func (*ListReadyStatesResponse) Descriptor() ([]byte, []int) {
	return file_party_proto_rawDescGZIP(), []int{13}
}

func (x *ListReadyStatesResponse) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *ListReadyStatesResponse) GetReadyStates() []*ReadyState {
	if x != nil {
		return x.ReadyStates
	}
	return nil
}

type ListMemberStatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	Members       []*MemberState         `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMemberStatesResponse) Reset() {
	*x = ListMemberStatesResponse{}
	mi := &file_party_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMemberStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemberStatesResponse) ProtoMessage() {}

func (x *ListMemberStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemberStatesResponse.ProtoReflect.Descriptor instead.
func (*ListMemberStatesResponse) Descriptor() ([]byte, []int) {
	return file_party_proto_rawDescGZIP(), []int{14}
}

func (x *ListMemberStatesResponse) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *ListMemberStatesResponse) GetMembers() []*MemberState {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_party_proto protoreflect.FileDescriptor

const file_party_proto_rawDesc = "" +
	"\n" +
	"\vparty.proto\x12\x17social_backend.party.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\finvite.proto\"\x8e\x01\n" +
	"\x05Party\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x03 \x03(\tR\tmemberIds\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x9a\x01\n" +
	"\n" +
	"ReadyState\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x19\n" +
	"\bis_ready\x18\x03 \x01(\bR\aisReady\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb4\x01\n" +
	"\n" +
	"QueueState\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\tjoined_by\x18\x04 \x01(\tR\bjoinedBy\x127\n" +
	"\tjoined_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\"\x99\x01\n" +
	"\x10QueueLeaveResult\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x123\n" +
	"\aleft_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06leftAt\"\xbd\x02\n" +
	"\fQueueHandoff\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x19\n" +
	"\bparty_id\x18\x02 \x01(\tR\apartyId\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x03 \x01(\tR\tqueueName\x12\x1b\n" +
	"\tleader_id\x18\x04 \x01(\tR\bleaderId\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x05 \x03(\tR\tmemberIds\x127\n" +
	"\tjoined_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x12!\n" +
	"\fmember_count\x18\a \x01(\x05R\vmemberCount\x12>\n" +
	"\amembers\x18\b \x03(\v2$.social_backend.party.v1.MemberStateR\amembers\"\xd4\x01\n" +
	"\vMemberState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1b\n" +
	"\tis_leader\x18\x02 \x01(\bR\bisLeader\x12\x19\n" +
	"\bis_ready\x18\x03 \x01(\bR\aisReady\x12\x1a\n" +
	"\bpresence\x18\x04 \x01(\tR\bpresence\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x19\n" +
	"\brealm_id\x18\x06 \x01(\tR\arealmId\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\"1\n" +
	"\x12CreatePartyRequest\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\tR\bleaderId\",\n" +
	"\x0fGetPartyRequest\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\"\x7f\n" +
	"\x18CreatePartyInviteRequest\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12&\n" +
	"\x0factor_player_id\x18\x02 \x01(\tR\ractorPlayerId\x12 \n" +
	"\fto_player_id\x18\x03 \x01(\tR\n" +
	"toPlayerId\"r\n" +
	"\x10JoinPartyRequest\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12\x1b\n" +
	"\tinvite_id\x18\x02 \x01(\tR\binviteId\x12&\n" +
	"\x0factor_player_id\x18\x03 \x01(\tR\ractorPlayerId\"o\n" +
	"\x0fSetReadyRequest\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12&\n" +
	"\x0factor_player_id\x18\x02 \x01(\tR\ractorPlayerId\x12\x19\n" +
	"\bis_ready\x18\x03 \x01(\bR\aisReady\"t\n" +
	"\x10JoinQueueRequest\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12&\n" +
	"\x0factor_player_id\x18\x02 \x01(\tR\ractorPlayerId\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x03 \x01(\tR\tqueueName\"V\n" +
	"\x11LeaveQueueRequest\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12&\n" +
	"\x0factor_player_id\x18\x02 \x01(\tR\ractorPlayerId\"|\n" +
	"\x17ListReadyStatesResponse\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12F\n" +
	"\fready_states\x18\x02 \x03(\v2#.social_backend.party.v1.ReadyStateR\vreadyStates\"u\n" +
	"\x18ListMemberStatesResponse\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12>\n" +
	"\amembers\x18\x02 \x03(\v2$.social_backend.party.v1.MemberStateR\amembers2\xc3\b\n" +
	"\fPartyService\x12Z\n" +
	"\vCreateParty\x12+.social_backend.party.v1.CreatePartyRequest\x1a\x1e.social_backend.party.v1.Party\x12T\n" +
	"\bGetParty\x12(.social_backend.party.v1.GetPartyRequest\x1a\x1e.social_backend.party.v1.Party\x12h\n" +
	"\x11CreatePartyInvite\x121.social_backend.party.v1.CreatePartyInviteRequest\x1a .social_backend.invite.v1.Invite\x12V\n" +
	"\tJoinParty\x12).social_backend.party.v1.JoinPartyRequest\x1a\x1e.social_backend.party.v1.Party\x12Y\n" +
	"\bSetReady\x12(.social_backend.party.v1.SetReadyRequest\x1a#.social_backend.party.v1.ReadyState\x12[\n" +
	"\tJoinQueue\x12).social_backend.party.v1.JoinQueueRequest\x1a#.social_backend.party.v1.QueueState\x12c\n" +
	"\n" +
	"LeaveQueue\x12*.social_backend.party.v1.LeaveQueueRequest\x1a).social_backend.party.v1.QueueLeaveResult\x12^\n" +
	"\rGetQueueState\x12(.social_backend.party.v1.GetPartyRequest\x1a#.social_backend.party.v1.QueueState\x12b\n" +
	"\x0fGetQueueHandoff\x12(.social_backend.party.v1.GetPartyRequest\x1a%.social_backend.party.v1.QueueHandoff\x12m\n" +
	"\x0fListReadyStates\x12(.social_backend.party.v1.GetPartyRequest\x1a0.social_backend.party.v1.ListReadyStatesResponse\x12o\n" +
	"\x10ListMemberStates\x12(.social_backend.party.v1.GetPartyRequest\x1a1.social_backend.party.v1.ListMemberStatesResponseB\xe2\x01\n" +
	"\x1bcom.social_backend.party.v1B\n" +
	"PartyProtoP\x01Z=github.com/xyun1996/social_backend/api/proto/party/v1;partyv1\xa2\x02\x03SPX\xaa\x02\x16SocialBackend.Party.V1\xca\x02\x16SocialBackend\\Party\\V1\xe2\x02\"SocialBackend\\Party\\V1\\GPBMetadata\xea\x02\x18SocialBackend::Party::V1b\x06proto3"

var (
	file_party_proto_rawDescOnce sync.Once
	file_party_proto_rawDescData []byte
)

func file_party_proto_rawDescGZIP() []byte {
	file_party_proto_rawDescOnce.Do(func() {
		file_party_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_party_proto_rawDesc), len(file_party_proto_rawDesc)))
	})
	return file_party_proto_rawDescData
}

var file_party_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_party_proto_goTypes = []any{
	(*Party)(nil),                    // 0: social_backend.party.v1.Party
	(*ReadyState)(nil),               // 1: social_backend.party.v1.ReadyState
	(*QueueState)(nil),               // 2: social_backend.party.v1.QueueState
	(*QueueLeaveResult)(nil),         // 3: social_backend.party.v1.QueueLeaveResult
	(*QueueHandoff)(nil),             // 4: social_backend.party.v1.QueueHandoff
	(*MemberState)(nil),              // 5: social_backend.party.v1.MemberState
	(*CreatePartyRequest)(nil),       // 6: social_backend.party.v1.CreatePartyRequest
	(*GetPartyRequest)(nil),          // 7: social_backend.party.v1.GetPartyRequest
	(*CreatePartyInviteRequest)(nil), // 8: social_backend.party.v1.CreatePartyInviteRequest
	(*JoinPartyRequest)(nil),         // 9: social_backend.party.v1.JoinPartyRequest
	(*SetReadyRequest)(nil),          // 10: social_backend.party.v1.SetReadyRequest
	(*JoinQueueRequest)(nil),         // 11: social_backend.party.v1.JoinQueueRequest
	(*LeaveQueueRequest)(nil),        // 12: social_backend.party.v1.LeaveQueueRequest
	(*ListReadyStatesResponse)(nil),  // 13: social_backend.party.v1.ListReadyStatesResponse
	(*ListMemberStatesResponse)(nil), // 14: social_backend.party.v1.ListMemberStatesResponse
	(*timestamppb.Timestamp)(nil),    // 15: google.protobuf.Timestamp
	(*v1.Invite)(nil),                // 16: social_backend.invite.v1.Invite
}
var file_party_proto_depIdxs = []int32{
	15, // 0: social_backend.party.v1.Party.created_at:type_name -> google.protobuf.Timestamp
	15, // 1: social_backend.party.v1.ReadyState.updated_at:type_name -> google.protobuf.Timestamp
	15, // 2: social_backend.party.v1.QueueState.joined_at:type_name -> google.protobuf.Timestamp
	15, // 3: social_backend.party.v1.QueueLeaveResult.left_at:type_name -> google.protobuf.Timestamp
	15, // 4: social_backend.party.v1.QueueHandoff.joined_at:type_name -> google.protobuf.Timestamp
	5,  // 5: social_backend.party.v1.QueueHandoff.members:type_name -> social_backend.party.v1.MemberState
	1,  // 6: social_backend.party.v1.ListReadyStatesResponse.ready_states:type_name -> social_backend.party.v1.ReadyState
	5,  // 7: social_backend.party.v1.ListMemberStatesResponse.members:type_name -> social_backend.party.v1.MemberState
	6,  // 8: social_backend.party.v1.PartyService.CreateParty:input_type -> social_backend.party.v1.CreatePartyRequest
	7,  // 9: social_backend.party.v1.PartyService.GetParty:input_type -> social_backend.party.v1.GetPartyRequest
	8,  // 10: social_backend.party.v1.PartyService.CreatePartyInvite:input_type -> social_backend.party.v1.CreatePartyInviteRequest
	9,  // 11: social_backend.party.v1.PartyService.JoinParty:input_type -> social_backend.party.v1.JoinPartyRequest
	10, // 12: social_backend.party.v1.PartyService.SetReady:input_type -> social_backend.party.v1.SetReadyRequest
	11, // 13: social_backend.party.v1.PartyService.JoinQueue:input_type -> social_backend.party.v1.JoinQueueRequest
	12, // 14: social_backend.party.v1.PartyService.LeaveQueue:input_type -> social_backend.party.v1.LeaveQueueRequest
	7,  // 15: social_backend.party.v1.PartyService.GetQueueState:input_type -> social_backend.party.v1.GetPartyRequest
	7,  // 16: social_backend.party.v1.PartyService.GetQueueHandoff:input_type -> social_backend.party.v1.GetPartyRequest
	7,  // 17: social_backend.party.v1.PartyService.ListReadyStates:input_type -> social_backend.party.v1.GetPartyRequest
	7,  // 18: social_backend.party.v1.PartyService.ListMemberStates:input_type -> social_backend.party.v1.GetPartyRequest
	0,  // 19: social_backend.party.v1.PartyService.CreateParty:output_type -> social_backend.party.v1.Party
	0,  // 20: social_backend.party.v1.PartyService.GetParty:output_type -> social_backend.party.v1.Party
	16, // 21: social_backend.party.v1.PartyService.CreatePartyInvite:output_type -> social_backend.invite.v1.Invite
	0,  // 22: social_backend.party.v1.PartyService.JoinParty:output_type -> social_backend.party.v1.Party
	1,  // 23: social_backend.party.v1.PartyService.SetReady:output_type -> social_backend.party.v1.ReadyState
	2,  // 24: social_backend.party.v1.PartyService.JoinQueue:output_type -> social_backend.party.v1.QueueState
	3,  // 25: social_backend.party.v1.PartyService.LeaveQueue:output_type -> social_backend.party.v1.QueueLeaveResult
	2,  // 26: social_backend.party.v1.PartyService.GetQueueState:output_type -> social_backend.party.v1.QueueState
	4,  // 27: social_backend.party.v1.PartyService.GetQueueHandoff:output_type -> social_backend.party.v1.QueueHandoff
	13, // 28: social_backend.party.v1.PartyService.ListReadyStates:output_type -> social_backend.party.v1.ListReadyStatesResponse
	14, // 29: social_backend.party.v1.PartyService.ListMemberStates:output_type -> social_backend.party.v1.ListMemberStatesResponse
	19, // [19:30] is the sub-list for method output_type
	8,  // [8:19] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_party_proto_init() }
func file_party_proto_init() {
	if File_party_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_party_proto_rawDesc), len(file_party_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_party_proto_goTypes,
		DependencyIndexes: file_party_proto_depIdxs,
		MessageInfos:      file_party_proto_msgTypes,
	}.Build()
	File_party_proto = out.File
	file_party_proto_goTypes = nil
	file_party_proto_depIdxs = nil
}
